//-------------------------------------------------------------------------
/*
Copyright (C) 1996, 2003 - 3D Realms Entertainment
Copyright (C) 2000, 2003 - Matt Saettler (EDuke Enhancements)
Copyright (C) 2004, 2007 - EDuke32 developers
Copyright (C) 2009 - dimag0g

This file is part of eRampage port for Redneck Rampage series, derived from EDuke32

eRampage is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/
//-------------------------------------------------------------------------

// Maybe this should be called "hacks.c" instead of "namesdyn.c"...

#include "build.h"
#include "duke3d.h"
#include "compat.h"
#include "names.h"


int32_t _SECTOREFFECTOR = SECTOREFFECTOR;
int32_t _ACTIVATOR = ACTIVATOR;
int32_t _TOUCHPLATE = TOUCHPLATE;
int32_t _ACTIVATORLOCKED = ACTIVATORLOCKED;
int32_t _DOORLOCK = DOORLOCK;
int32_t _MUSICANDSFX = MUSICANDSFX;
int32_t _LOCATORS = LOCATORS;
int32_t _CYCLER = CYCLER;
int32_t _MASTERSWITCH = MASTERSWITCH;
int32_t _RESPAWN = RESPAWN;
int32_t _GPSPEED = GPSPEED;
int32_t _FOF = FOF;
int32_t _ARROW = ARROW;
int32_t _SHADESECTOR = SHADESECTOR;
int32_t _FIRSTGUNSPRITE = FIRSTGUNSPRITE;
int32_t _CHAINGUNSPRITE = CHAINGUNSPRITE;
int32_t _RPGSPRITE = RPGSPRITE;
int32_t _BUZSAWSPRITE = BUZSAWSPRITE;
int32_t _ALIENARMGUNSPRITE = ALIENARMGUNSPRITE;
int32_t _HEAVYHBOMB = HEAVYHBOMB;
int32_t _POWDERKEGSPRITE = POWDERKEGSPRITE;
int32_t _SHOTGUNSPRITE = SHOTGUNSPRITE;
int32_t _TEATGUNSPRITE = TEATGUNSPRITE;
int32_t _HEALTHBOX = HEALTHBOX;
int32_t _AMMOBOX = AMMOBOX;
int32_t _GROWSPRITEICON = GROWSPRITEICON;
int32_t _INVENTORYBOX = INVENTORYBOX;
int32_t _BUZSAWAMMO = BUZSAWAMMO;
int32_t _AMMO = AMMO;
int32_t _BATTERYAMMO = BATTERYAMMO;
int32_t _TEATGUNAMMO = TEATGUNAMMO;
int32_t _RPGAMMO = RPGAMMO;
int32_t _GROWAMMO = GROWAMMO;
int32_t _ALIENBLASTERAMMO = ALIENBLASTERAMMO;
int32_t _HBOMBAMMO = HBOMBAMMO;
int32_t _AMMOLOTS = AMMOLOTS;
int32_t _SHOTGUNAMMO = SHOTGUNAMMO;
int32_t _COLA = COLA;
int32_t _SIXPAK = SIXPAK;
int32_t _FIRSTAID = FIRSTAID;
int32_t _SHIELD = SHIELD;
int32_t _STEROIDS = STEROIDS;
int32_t _AIRTANK = AIRTANK;
int32_t _JETPACK = JETPACK;
int32_t _HEATSENSOR = HEATSENSOR;
int32_t _ACCESSCARD = ACCESSCARD;
int32_t _BOOTS = BOOTS;
int32_t _MIRRORBROKE = MIRRORBROKE;
int32_t _CLOUDYOCEAN = CLOUDYOCEAN;
int32_t _CLOUDYSKIES = CLOUDYSKIES;
int32_t _MOONSKY1 = MOONSKY1;
int32_t _MOONSKY2 = MOONSKY2;
int32_t _MOONSKY3 = MOONSKY3;
int32_t _MOONSKY4 = MOONSKY4;
int32_t _BIGORBIT1 = BIGORBIT1;
int32_t _BIGORBIT2 = BIGORBIT2;
int32_t _BIGORBIT3 = BIGORBIT3;
int32_t _BIGORBIT4 = BIGORBIT4;
int32_t _BIGORBIT5 = BIGORBIT5;
int32_t _LA = LA;
int32_t _REDSKY1 = REDSKY1;
int32_t _REDSKY2 = REDSKY2;
int32_t _ATOMICHEALTH = ATOMICHEALTH;
int32_t _TECHLIGHT2 = TECHLIGHT2;
int32_t _TECHLIGHTBUST2 = TECHLIGHTBUST2;
int32_t _TECHLIGHT4 = TECHLIGHT4;
int32_t _TECHLIGHTBUST4 = TECHLIGHTBUST4;
int32_t _WALLLIGHT4 = WALLLIGHT4;
int32_t _WALLLIGHTBUST4 = WALLLIGHTBUST4;
int32_t _ACCESSSWITCH = ACCESSSWITCH;
int32_t _SLOTDOOR = SLOTDOOR;
int32_t _LIGHTSWITCH = LIGHTSWITCH;
int32_t _SPACEDOORSWITCH = SPACEDOORSWITCH;
int32_t _SPACELIGHTSWITCH = SPACELIGHTSWITCH;
int32_t _FRANKENSTINESWITCH = FRANKENSTINESWITCH;
int32_t _NUKEBUTTON = NUKEBUTTON;
int32_t _MULTISWITCH = MULTISWITCH;
int32_t _MULTISWITCH2 = MULTISWITCH2;
int32_t _DOORTILE5 = DOORTILE5;
int32_t _DOORTILE6 = DOORTILE6;
int32_t _DOORTILE1 = DOORTILE1;
int32_t _DOORTILE2 = DOORTILE2;
int32_t _DOORTILE3 = DOORTILE3;
int32_t _DOORTILE4 = DOORTILE4;
int32_t _DOORTILE7 = DOORTILE7;
int32_t _DOORTILE8 = DOORTILE8;
int32_t _DOORTILE9 = DOORTILE9;
int32_t _DOORTILE10 = DOORTILE10;
int32_t _DOORSHOCK = DOORSHOCK;
int32_t _DIPSWITCH = DIPSWITCH;
int32_t _DIPSWITCH2 = DIPSWITCH2;
int32_t _TECHSWITCH = TECHSWITCH;
int32_t _DIPSWITCH3 = DIPSWITCH3;
int32_t _ACCESSSWITCH2 = ACCESSSWITCH2;
int32_t _REFLECTWATERTILE = REFLECTWATERTILE;
int32_t _FLOORSLIME = FLOORSLIME;
int32_t _BIGFORCE = BIGFORCE;
int32_t _EPISODE = EPISODE;
int32_t _MASKWALL9 = MASKWALL9;
int32_t _W_LIGHT = W_LIGHT;
int32_t _SCREENBREAK1 = SCREENBREAK1;
int32_t _SCREENBREAK2 = SCREENBREAK2;
int32_t _SCREENBREAK3 = SCREENBREAK3;
int32_t _SCREENBREAK4 = SCREENBREAK4;
int32_t _SCREENBREAK5 = SCREENBREAK5;
int32_t _SCREENBREAK6 = SCREENBREAK6;
int32_t _SCREENBREAK7 = SCREENBREAK7;
int32_t _SCREENBREAK8 = SCREENBREAK8;
int32_t _SCREENBREAK9 = SCREENBREAK9;
int32_t _SCREENBREAK10 = SCREENBREAK10;
int32_t _SCREENBREAK11 = SCREENBREAK11;
int32_t _SCREENBREAK12 = SCREENBREAK12;
int32_t _SCREENBREAK13 = SCREENBREAK13;
int32_t _MASKWALL1 = MASKWALL1;
int32_t _W_TECHWALL1 = W_TECHWALL1;
int32_t _W_TECHWALL2 = W_TECHWALL2;
int32_t _W_TECHWALL15 = W_TECHWALL15;
int32_t _W_TECHWALL3 = W_TECHWALL3;
int32_t _W_TECHWALL4 = W_TECHWALL4;
int32_t _W_TECHWALL10 = W_TECHWALL10;
int32_t _W_TECHWALL16 = W_TECHWALL16;
int32_t _WATERTILE2 = WATERTILE2;
int32_t _BPANNEL1 = BPANNEL1;
int32_t _PANNEL1 = PANNEL1;
int32_t _PANNEL2 = PANNEL2;
int32_t _WATERTILE = WATERTILE;
int32_t _STATIC = STATIC;
int32_t _W_SCREENBREAK =  W_SCREENBREAK;
int32_t _W_HITTECHWALL3 = W_HITTECHWALL3;
int32_t _W_HITTECHWALL4 = W_HITTECHWALL4;
int32_t _W_HITTECHWALL2 = W_HITTECHWALL2;
int32_t _W_HITTECHWALL1 = W_HITTECHWALL1;
int32_t _MASKWALL10 = MASKWALL10;
int32_t _MASKWALL11 = MASKWALL11;
int32_t _DOORTILE22 = DOORTILE22;
int32_t _FANSPRITE = FANSPRITE;
int32_t _FANSPRITEBROKE = FANSPRITEBROKE;
int32_t _FANSHADOW = FANSHADOW;
int32_t _FANSHADOWBROKE = FANSHADOWBROKE;
int32_t _DOORTILE18 = DOORTILE18;
int32_t _DOORTILE19 = DOORTILE19;
int32_t _DOORTILE20 = DOORTILE20;
int32_t _SATELLITE = SATELLITE;
int32_t _VIEWSCREEN2 = VIEWSCREEN2;
int32_t _VIEWSCREENBROKE = VIEWSCREENBROKE;
int32_t _VIEWSCREEN = VIEWSCREEN;
int32_t _GLASS = GLASS;
int32_t _GLASS2 = GLASS2;
int32_t _STAINGLASS1 = STAINGLASS1;
int32_t _MASKWALL5 = MASKWALL5;
int32_t _SATELITE = SATELITE;
int32_t _FUELPOD = FUELPOD;
int32_t _SLIMEPIPE = SLIMEPIPE;
int32_t _CRACK1 = CRACK1;
int32_t _CRACK2 = CRACK2;
int32_t _CRACK3 = CRACK3;
int32_t _CRACK4 = CRACK4;
int32_t _FOOTPRINTS = FOOTPRINTS;
int32_t _DOMELITE = DOMELITE;
int32_t _CAMERAPOLE = CAMERAPOLE;
int32_t _CHAIR1 = CHAIR1;
int32_t _CHAIR2 = CHAIR2;
int32_t _BROKENCHAIR = BROKENCHAIR;
int32_t _MIRROR = MIRROR;
int32_t _WATERFOUNTAIN = WATERFOUNTAIN;
int32_t _WATERFOUNTAINBROKE = WATERFOUNTAINBROKE;
int32_t _FEMMAG1 = FEMMAG1;
int32_t _TOILET = TOILET;
int32_t _STALL = STALL;
int32_t _STALLBROKE = STALLBROKE;
int32_t _FEMMAG2 = FEMMAG2;
int32_t _REACTOR2 = REACTOR2;
int32_t _REACTOR2BURNT = REACTOR2BURNT;
int32_t _REACTOR2SPARK = REACTOR2SPARK;
int32_t _GRATE1 = GRATE1;
int32_t _BGRATE1 = BGRATE1;
int32_t _SOLARPANNEL = SOLARPANNEL;
int32_t _NAKED1 = NAKED1;
int32_t _ANTENNA = ANTENNA;
int32_t _MASKWALL12 = MASKWALL12;
int32_t _TOILETBROKE = TOILETBROKE;
int32_t _PIPE2 = PIPE2;
int32_t _PIPE1B = PIPE1B;
int32_t _PIPE3 = PIPE3;
int32_t _PIPE1 = PIPE1;
int32_t _CAMERA1 = CAMERA1;
int32_t _BRICK = BRICK;
int32_t _SPLINTERWOOD = SPLINTERWOOD;
int32_t _PIPE2B = PIPE2B;
int32_t _BOLT1 = BOLT1;
int32_t _W_NUMBERS = W_NUMBERS;
int32_t _WATERDRIP = WATERDRIP;
int32_t _WATERBUBBLE = WATERBUBBLE;
int32_t _WATERBUBBLEMAKER = WATERBUBBLEMAKER;
int32_t _W_FORCEFIELD = W_FORCEFIELD;
int32_t _VACUUM = VACUUM;
int32_t _FOOTPRINTS2 = FOOTPRINTS2;
int32_t _FOOTPRINTS3 = FOOTPRINTS3;
int32_t _FOOTPRINTS4 = FOOTPRINTS4;
int32_t _EGG = EGG;
int32_t _SCALE = SCALE;
int32_t _CHAIR3 = CHAIR3;
int32_t _CAMERALIGHT = CAMERALIGHT;
int32_t _MOVIECAMERA = MOVIECAMERA;
int32_t _IVUNIT = IVUNIT;
int32_t _POT1 = POT1;
int32_t _POT2 = POT2;
int32_t _POT3 = POT3;
int32_t _PIPE3B = PIPE3B;
int32_t _WALLLIGHT3 = WALLLIGHT3;
int32_t _WALLLIGHTBUST3 = WALLLIGHTBUST3;
int32_t _WALLLIGHT1 = WALLLIGHT1;
int32_t _WALLLIGHTBUST1 = WALLLIGHTBUST1;
int32_t _WALLLIGHT2 = WALLLIGHT2;
int32_t _WALLLIGHTBUST2 = WALLLIGHTBUST2;
int32_t _LIGHTSWITCH2 = LIGHTSWITCH2;
int32_t _WAITTOBESEATED = WAITTOBESEATED;
int32_t _DOORTILE14 = DOORTILE14;
int32_t _STATUE = STATUE;
int32_t _MIKE = MIKE;
int32_t _VASE = VASE;
int32_t _SUSHIPLATE1 = SUSHIPLATE1;
int32_t _SUSHIPLATE2 = SUSHIPLATE2;
int32_t _SUSHIPLATE3 = SUSHIPLATE3;
int32_t _SUSHIPLATE4 = SUSHIPLATE4;
int32_t _DOORTILE16 = DOORTILE16;
int32_t _SUSHIPLATE5 = SUSHIPLATE5;
int32_t _OJ = OJ;
int32_t _MASKWALL13 = MASKWALL13;
int32_t _HURTRAIL = HURTRAIL;
int32_t _POWERSWITCH1 = POWERSWITCH1;
int32_t _LOCKSWITCH1 = LOCKSWITCH1;
int32_t _POWERSWITCH2 = POWERSWITCH2;
int32_t _ATM = ATM;
int32_t _STATUEFLASH = STATUEFLASH;
int32_t _ATMBROKE = ATMBROKE;
int32_t _BIGHOLE2 = BIGHOLE2;
int32_t _STRIPEBALL = STRIPEBALL;
int32_t _QUEBALL = QUEBALL;
int32_t _POCKET = POCKET;
int32_t _WOODENHORSE = WOODENHORSE;
int32_t _TREE1 = TREE1;
int32_t _TREE2 = TREE2;
int32_t _CACTUS = CACTUS;
int32_t _MASKWALL2 = MASKWALL2;
int32_t _MASKWALL3 = MASKWALL3;
int32_t _MASKWALL4 = MASKWALL4;
int32_t _FIREEXT = FIREEXT;
int32_t _TOILETWATER = TOILETWATER;
int32_t _NEON1 = NEON1;
int32_t _NEON2 = NEON2;
int32_t _CACTUSBROKE = CACTUSBROKE;
int32_t _BOUNCEMINE = BOUNCEMINE;
int32_t _BROKEFIREHYDRENT = BROKEFIREHYDRENT;
int32_t _BOX = BOX;
int32_t _BULLETHOLE = BULLETHOLE;
int32_t _BOTTLE1 = BOTTLE1;
int32_t _BOTTLE2 = BOTTLE2;
int32_t _BOTTLE3 = BOTTLE3;
int32_t _BOTTLE4 = BOTTLE4;
int32_t _FEMPIC5 = FEMPIC5;
int32_t _FEMPIC6 = FEMPIC6;
int32_t _FEMPIC7 = FEMPIC7;
int32_t _HYDROPLANT = HYDROPLANT;
int32_t _OCEANSPRITE1 = OCEANSPRITE1;
int32_t _OCEANSPRITE2 = OCEANSPRITE2;
int32_t _OCEANSPRITE3 = OCEANSPRITE3;
int32_t _OCEANSPRITE4 = OCEANSPRITE4;
int32_t _OCEANSPRITE5 = OCEANSPRITE5;
int32_t _GENERICPOLE = GENERICPOLE;
int32_t _CONE = CONE;
int32_t _HANGLIGHT = HANGLIGHT;
int32_t _HYDRENT = HYDRENT;
int32_t _MASKWALL14 = MASKWALL14;
int32_t _TIRE = TIRE;
int32_t _PIPE5 = PIPE5;
int32_t _PIPE6 = PIPE6;
int32_t _PIPE4 = PIPE4;
int32_t _PIPE4B = PIPE4B;
int32_t _BROKEHYDROPLANT = BROKEHYDROPLANT;
int32_t _PIPE5B = PIPE5B;
int32_t _NEON3 = NEON3;
int32_t _NEON4 = NEON4;
int32_t _NEON5 = NEON5;
int32_t _BOTTLE5 = BOTTLE5;
int32_t _BOTTLE6 = BOTTLE6;
int32_t _BOTTLE8 = BOTTLE8;
int32_t _SPOTLITE = SPOTLITE;
int32_t _HANGOOZ = HANGOOZ;
int32_t _MASKWALL15 = MASKWALL15;
int32_t _BOTTLE7 = BOTTLE7;
int32_t _HORSEONSIDE = HORSEONSIDE;
int32_t _GLASSPIECES = GLASSPIECES;
int32_t _HORSELITE = HORSELITE;
int32_t _DONUTS = DONUTS;
int32_t _NEON6 = NEON6;
int32_t _MASKWALL6 = MASKWALL6;
int32_t _CLOCK = CLOCK;
int32_t _RUBBERCAN = RUBBERCAN;
int32_t _BROKENCLOCK = BROKENCLOCK;
int32_t _PLUG = PLUG;
int32_t _OOZFILTER = OOZFILTER;
int32_t _FLOORPLASMA = FLOORPLASMA;
int32_t _REACTOR = REACTOR;
int32_t _REACTORSPARK = REACTORSPARK;
int32_t _REACTORBURNT = REACTORBURNT;
int32_t _DOORTILE15 = DOORTILE15;
int32_t _HANDSWITCH = HANDSWITCH;
int32_t _CIRCLEPANNEL = CIRCLEPANNEL;
int32_t _CIRCLEPANNELBROKE = CIRCLEPANNELBROKE;
int32_t _PULLSWITCH = PULLSWITCH;
int32_t _MASKWALL8 = MASKWALL8;
int32_t _BIGHOLE = BIGHOLE;
int32_t _ALIENSWITCH = ALIENSWITCH;
int32_t _DOORTILE21 = DOORTILE21;
int32_t _HANDPRINTSWITCH = HANDPRINTSWITCH;
int32_t _BOTTLE10 = BOTTLE10;
int32_t _BOTTLE11 = BOTTLE11;
int32_t _BOTTLE12 = BOTTLE12;
int32_t _BOTTLE13 = BOTTLE13;
int32_t _BOTTLE14 = BOTTLE14;
int32_t _BOTTLE15 = BOTTLE15;
int32_t _BOTTLE16 = BOTTLE16;
int32_t _BOTTLE17 = BOTTLE17;
int32_t _BOTTLE18 = BOTTLE18;
int32_t _BOTTLE19 = BOTTLE19;
int32_t _DOORTILE17 = DOORTILE17;
int32_t _MASKWALL7 = MASKWALL7;
int32_t _JAILBARBREAK = JAILBARBREAK;
int32_t _DOORTILE11 = DOORTILE11;
int32_t _DOORTILE12 = DOORTILE12;
int32_t _VENDMACHINE = VENDMACHINE;
int32_t _VENDMACHINEBROKE = VENDMACHINEBROKE;
int32_t _COLAMACHINE = COLAMACHINE;
int32_t _COLAMACHINEBROKE = COLAMACHINEBROKE;
int32_t _CRANEPOLE = CRANEPOLE;
int32_t _CRANE = CRANE;
int32_t _BARBROKE = BARBROKE;
int32_t _BLOODPOOL = BLOODPOOL;
int32_t _NUKEBARREL = NUKEBARREL;
int32_t _NUKEBARRELDENTED = NUKEBARRELDENTED;
int32_t _NUKEBARRELLEAKED = NUKEBARRELLEAKED;
int32_t _CANWITHSOMETHING = CANWITHSOMETHING;
int32_t _MONEY = MONEY;
int32_t _BANNER = BANNER;
int32_t _EXPLODINGBARREL = EXPLODINGBARREL;
int32_t _EXPLODINGBARREL2 = EXPLODINGBARREL2;
int32_t _FIREBARREL = FIREBARREL;
int32_t _SEENINE = SEENINE;
int32_t _SEENINEDEAD = SEENINEDEAD;
int32_t _STEAM = STEAM;
int32_t _CEILINGSTEAM = CEILINGSTEAM;
int32_t _PIPE6B = PIPE6B;
int32_t _TRANSPORTERBEAM = TRANSPORTERBEAM;
int32_t _RAT = RAT;
int32_t _TRASH = TRASH;
int32_t _FEMPIC1 = FEMPIC1;
int32_t _FEMPIC2 = FEMPIC2;
int32_t _BLANKSCREEN = BLANKSCREEN;
int32_t _PODFEM1 = PODFEM1;
int32_t _FEMPIC3 = FEMPIC3;
int32_t _FEMPIC4 = FEMPIC4;
int32_t _FEM1 = FEM1;
int32_t _FEM2 = FEM2;
int32_t _FEM3 = FEM3;
int32_t _FEM5 = FEM5;
int32_t _BLOODYPOLE = BLOODYPOLE;
int32_t _FEM4 = FEM4;
int32_t _FEM6 = FEM6;
int32_t _FEM6PAD = FEM6PAD;
int32_t _FEM8 = FEM8;
int32_t _HELECOPT = HELECOPT;
int32_t _FETUSJIB = FETUSJIB;
int32_t _HOLODUKE = HOLODUKE;
int32_t _SPACEMARINE = SPACEMARINE;
int32_t _INDY = INDY;
int32_t _FETUS = FETUS;
int32_t _FETUSBROKE = FETUSBROKE;
int32_t _MONK = MONK;
int32_t _LUKE = LUKE;
int32_t _COOLEXPLOSION1 = COOLEXPLOSION1;
int32_t _WATERSPLASH2 = WATERSPLASH2;
int32_t _FIREVASE = FIREVASE;
int32_t _SCRATCH = SCRATCH;
int32_t _FEM7 = FEM7;
int32_t _APLAYERTOP = APLAYERTOP;
int32_t _APLAYER = APLAYER;
int32_t _PLAYERONWATER = PLAYERONWATER;
int32_t _DUKELYINGDEAD = DUKELYINGDEAD;
int32_t _DUKETORSO = DUKETORSO;
int32_t _DUKEGUN = DUKEGUN;
int32_t _DUKELEG = DUKELEG;

int32_t _BLOOD = BLOOD;
int32_t _FIRELASER = FIRELASER;
int32_t _TRANSPORTERSTAR = TRANSPORTERSTAR;
int32_t _SPIT = SPIT;
int32_t _LOOGIE = LOOGIE;
int32_t _FIST = FIST;
int32_t _CIRCLESAW = CIRCLESAW;
int32_t _TEATGUNBLAST = TEATGUNBLAST;
int32_t _TONGUE = TONGUE;
int32_t _MORTER = MORTER;
int32_t _ALIENARMGUNEXPLOSION = ALIENARMGUNEXPLOSION;
int32_t _RADIUSEXPLOSION = RADIUSEXPLOSION;
int32_t _FORCERIPPLE = FORCERIPPLE;


/*
int32_t _HEADJIB1 = HEADJIB1;
int32_t _ARMJIB1 = ARMJIB1;
int32_t _LEGJIB1 = LEGJIB1;
int32_t _LIZMANHEAD1 = LIZMANHEAD1;
int32_t _LIZMANARM1 = LIZMANARM1;
int32_t _LIZMANLEG1 = LIZMANLEG1;
//*/
int32_t _FBOATJIBA = FBOATJIBA;
int32_t _FBOATJIBB = FBOATJIBB;
int32_t _CHEERJIBA = CHEERJIBA;
int32_t _CHEERJIBB = CHEERJIBB;
int32_t _CHEERJIBC = CHEERJIBC;
int32_t _CHEERJIBD = CHEERJIBD;
int32_t _RABBITJIBA = RABBITJIBA;
int32_t _RABBITJIBB = RABBITJIBB;
int32_t _RABBITJIBC = RABBITJIBC;
int32_t _MINJIBA = MINJIBA;
int32_t _MINJIBB = MINJIBB;
int32_t _MINJIBC = MINJIBC;
int32_t _HULKJIBA = HULKJIBA;
int32_t _HULKJIBB = HULKJIBB;
int32_t _HULKJIBC = HULKJIBC;
int32_t _BILLYJIBA = BILLYJIBA;
int32_t _BILLYJIBB = BILLYJIBB;
int32_t _COOTJIBA = COOTJIBA;
int32_t _COOTJIBB = COOTJIBB;
int32_t _COOTJIBC = COOTJIBC;
int32_t _BIKEJIBA = BIKEJIBA;
int32_t _BIKEJIBB = BIKEJIBB;
int32_t _BIKEJIBC = BIKEJIBC;
int32_t _BIKERJIBA = BIKERJIBA;
int32_t _BIKERJIBB = BIKERJIBB;
int32_t _BIKERJIBC = BIKERJIBC;
int32_t _BIKERJIBD = BIKERJIBD;
int32_t _MAMAJIBA = MAMAJIBA;
int32_t _MAMAJIBB = MAMAJIBB;


/*
int32_t _BOSS1 = BOSS1;
int32_t _BOSS1STAYPUT = BOSS1STAYPUT;
int32_t _BOSS1SHOOT = BOSS1SHOOT;
int32_t _BOSS1LOB = BOSS1LOB;
int32_t _BOSSTOP = BOSSTOP;
int32_t _BOSS2 = BOSS2;
int32_t _BOSS3 = BOSS3;
int32_t _LIZTROOP = LIZTROOP;
int32_t _LIZTROOPRUNNING = LIZTROOPRUNNING;
int32_t _LIZTROOPSTAYPUT = LIZTROOPSTAYPUT;
int32_t _LIZTOP = LIZTOP;
int32_t _LIZTROOPSHOOT = LIZTROOPSHOOT;
int32_t _LIZTROOPJETPACK = LIZTROOPJETPACK;
int32_t _LIZTROOPDSPRITE = LIZTROOPDSPRITE;
int32_t _LIZTROOPONTOILET = LIZTROOPONTOILET;
int32_t _LIZTROOPJUSTSIT = LIZTROOPJUSTSIT;
int32_t _LIZTROOPDUCKING = LIZTROOPDUCKING;

int32_t _OCTABRAIN = OCTABRAIN;
int32_t _OCTABRAINSTAYPUT = OCTABRAINSTAYPUT;
int32_t _OCTATOP = OCTATOP;
int32_t _OCTADEADSPRITE = OCTADEADSPRITE;
int32_t _DRONE = DRONE;
int32_t _COMMANDER = COMMANDER;
int32_t _COMMANDERSTAYPUT = COMMANDERSTAYPUT;
int32_t _RECON = RECON;
int32_t _TANK = TANK;
int32_t _PIGCOP = PIGCOP;
int32_t _PIGCOPSTAYPUT = PIGCOPSTAYPUT;
int32_t _PIGCOPDIVE = PIGCOPDIVE;
int32_t _PIGCOPDEADSPRITE = PIGCOPDEADSPRITE;
int32_t _PIGTOP = PIGTOP;
int32_t _LIZMAN = LIZMAN;
int32_t _LIZMANSTAYPUT = LIZMANSTAYPUT;
int32_t _LIZMANSPITTING = LIZMANSPITTING;
int32_t _LIZMANFEEDING = LIZMANFEEDING;
int32_t _LIZMANJUMP = LIZMANJUMP;
int32_t _LIZMANDEADSPRITE = LIZMANDEADSPRITE;
int32_t _FECES = FECES;


int32_t _NEWBEAST = NEWBEAST;
int32_t _NEWBEASTSTAYPUT = NEWBEASTSTAYPUT;
int32_t _NEWBEASTJUMP = NEWBEASTJUMP;
int32_t _NEWBEASTHANG = NEWBEASTHANG;
int32_t _NEWBEASTHANGDEAD = NEWBEASTHANGDEAD;
int32_t _BOSS4 = BOSS4;
int32_t _BOSS4STAYPUT = BOSS4STAYPUT;
/*/
int32_t _COOT = COOT;
int32_t _COOTSTAYPUT = COOTSTAYPUT;
int32_t _COOTSHOOT = COOTSHOOT;
int32_t _COOTDIE = COOTDIE;
int32_t _COOTDUCK = COOTDUCK;
int32_t _COOTPAIN = COOTPAIN;
int32_t _COOTTRANS = COOTTRANS;
int32_t _COOTGETUP = COOTGETUP;
int32_t _ECLAIRHEALTH = ECLAIRHEALTH;
int32_t _BILLYWALK = BILLYWALK;
int32_t _BILLYDIE = BILLYDIE;
int32_t _BILLYCOCK = BILLYCOCK;
int32_t _BILLYRAY = BILLYRAY;
int32_t _BILLYSHOOT = BILLYSHOOT;
int32_t _BILLYRAYSTAYPUT = BILLYRAYSTAYPUT;
int32_t _BILLYBUT = BILLYBUT;
int32_t _BILLYSCRATCH = BILLYSCRATCH;
int32_t _BILLYSNIFF = BILLYSNIFF;
int32_t _BILLYWOUND = BILLYWOUND;
int32_t _BILLYGORE = BILLYGORE;
int32_t _DOGRUN = DOGRUN;
int32_t _DOGDIE = DOGDIE;
int32_t _DOGDEAD = DOGDEAD;
int32_t _DOGBARK = DOGBARK;
int32_t _DOGATTACK = DOGATTACK;
int32_t _LTH = LTH;
int32_t _LTHSTRAFE = LTHSTRAFE;
int32_t _LTHLOAD = LTHLOAD;
int32_t _LTHDIE = LTHDIE;

int32_t _BUBBASCRATCH = BUBBASCRATCH;
int32_t _BUBBANOSE = BUBBANOSE;
int32_t _BUBBAPISS = BUBBAPISS;
int32_t _BUBBASTAND = BUBBASTAND;
int32_t _BUBBAOUCH = BUBBAOUCH;
int32_t _BUBBADIE = BUBBADIE;
int32_t _BUBBADEAD = BUBBADEAD;

int32_t _HULK = HULK;
int32_t _HULKSTAYPUT = HULKSTAYPUT;
int32_t _HULKA = HULKA;
int32_t _HULKB = HULKB;
int32_t _HULKC = HULKC;
int32_t _SBSWIPE = SBSWIPE;
int32_t _SBPAIN = SBPAIN;
int32_t _SBDIE = SBDIE;
int32_t _HEN = HEN;
int32_t _HENSTAYPUT = HENSTAYPUT;
int32_t _HENSTAND = HENSTAND;
int32_t _MOSQUITO = MOSQUITO;
int32_t _PIG = PIG;
int32_t _PIGSTAYPUT = PIGSTAYPUT;
int32_t _PIGEAT = PIGEAT;
int32_t _SBMOVE = SBMOVE;
int32_t _SBSPIT = SBSPIT;
int32_t _SBDIP = SBDIP;
int32_t _MINION = MINION;
int32_t _MINIONSTAYPUT = MINIONSTAYPUT;
int32_t _UFO1 = UFO1;
int32_t _UFO2 = UFO2;
int32_t _UFO3 = UFO3;
int32_t _UFO4 = UFO4;
int32_t _UFO5 = UFO5;
int32_t _COW = COW;


int32_t _VIXEN = VIXEN;
int32_t _VIXENPAIN = VIXENPAIN;
int32_t _VIXENDIE = VIXENDIE;
int32_t _VIXENSHOOT = VIXENSHOOT;
int32_t _VIXENWDN = VIXENWDN;
int32_t _VIXENWUP = VIXENWUP;
int32_t _VIXENKICK = VIXENKICK;
int32_t _VIXENTELE = VIXENTELE;
int32_t _VIXENTEAT = VIXENTEAT;

int32_t _MOTOHIT = MOTOHIT;
int32_t _BOATHIT = BOATHIT;
int32_t _EMPTYBIKE = EMPTYBIKE;
int32_t _EMPTYBOAT = EMPTYBOAT;

int32_t _RABBIT = RABBIT;
int32_t _MAKEOUT = MAKEOUT;

int32_t _DEADBIKE = DEADBIKE;
int32_t _CHEER = CHEER;
int32_t _CHEERSTAYPUT = CHEERSTAYPUT;
int32_t _CHEERB = CHEERB;
int32_t _CHEERBOMB = CHEERBOMB;
int32_t _CHEERBLADE = CHEERBLADE;
int32_t _MOTOGUN = MOTOGUN;
int32_t _MOTOAMMO = MOTOAMMO;
int32_t _BOATAMMO = BOATAMMO;
int32_t _WEED = WEED;
int32_t _BIKERB = BIKERB;
int32_t _BIKERBV2 = BIKERBV2;
int32_t _BIKER = BIKER;
int32_t _MINIONBOAT = MINIONBOAT;
int32_t _HULKBOAT = HULKBOAT;
int32_t _CHEERBOAT = CHEERBOAT;

int32_t _MAMA = MAMA;
int32_t _MAMACLOUD = MAMACLOUD;

int32_t _COOTPLAY = COOTPLAY;
int32_t _BILLYPLAY = BILLYPLAY;
//*/


int32_t _CANNONBALL = CANNONBALL;
int32_t _INNERJAW = INNERJAW;
int32_t _EXPLOSION2 = EXPLOSION2;

int32_t _EXPLOSION2BOT = EXPLOSION2BOT;
int32_t _USERWEAPON = USERWEAPON;
int32_t _HEADERBAR = HEADERBAR;
int32_t _JIBS1 = JIBS1;
int32_t _JIBS2 = JIBS2;
int32_t _JIBS3 = JIBS3;
int32_t _JIBS4 = JIBS4;
int32_t _JIBS5 = JIBS5;
int32_t _BURNING = BURNING;
int32_t _FIRE = FIRE;
int32_t _JIBS6 = JIBS6;
int32_t _BLOODSPLAT1 = BLOODSPLAT1;
int32_t _BLOODSPLAT3 = BLOODSPLAT3;
int32_t _BLOODSPLAT2 = BLOODSPLAT2;
int32_t _BLOODSPLAT4 = BLOODSPLAT4;
int32_t _OOZ = OOZ;
int32_t _OOZ2 = OOZ2;
int32_t _WALLBLOOD1 = WALLBLOOD1;
int32_t _WALLBLOOD2 = WALLBLOOD2;
int32_t _WALLBLOOD3 = WALLBLOOD3;
int32_t _WALLBLOOD4 = WALLBLOOD4;
int32_t _WALLBLOOD5 = WALLBLOOD5;
int32_t _WALLBLOOD6 = WALLBLOOD6;
int32_t _WALLBLOOD7 = WALLBLOOD7;
int32_t _WALLBLOOD8 = WALLBLOOD8;
int32_t _BURNING2 = BURNING2;
int32_t _FIRE2 = FIRE2;
int32_t _CRACKKNUCKLES = CRACKKNUCKLES;
int32_t _SMALLSMOKE = SMALLSMOKE;
int32_t _SMALLSMOKEMAKER = SMALLSMOKEMAKER;
int32_t _FLOORFLAME = FLOORFLAME;
int32_t _ROTATEGUN = ROTATEGUN;
int32_t _GREENSLIME = GREENSLIME;
int32_t _WATERDRIPSPLASH = WATERDRIPSPLASH;
int32_t _SCRAP6 = SCRAP6;
int32_t _SCRAP1 = SCRAP1;
int32_t _SCRAP2 = SCRAP2;
int32_t _SCRAP3 = SCRAP3;
int32_t _SCRAP4 = SCRAP4;
int32_t _SCRAP5 = SCRAP5;

int32_t _BETAVERSION = BETAVERSION;
int32_t _PLAYERISHERE = PLAYERISHERE;
int32_t _PLAYERWASHERE = PLAYERWASHERE;
int32_t _SELECTDIR = SELECTDIR;
int32_t _F1HELP = F1HELP;
int32_t _NOTCHON = NOTCHON;
int32_t _NOTCHOFF = NOTCHOFF;
int32_t _GROWSPARK = GROWSPARK;
int32_t _DUKEICON = DUKEICON;
int32_t _BADGUYICON = BADGUYICON;
int32_t _FOODICON = FOODICON;
int32_t _GETICON = GETICON;
int32_t _MENUSCREEN = MENUSCREEN;
int32_t _MENUBAR = MENUBAR;
int32_t _KILLSICON = KILLSICON;
int32_t _FIRSTAID_ICON = FIRSTAID_ICON;
int32_t _HEAT_ICON = HEAT_ICON;
int32_t _BOTTOMSTATUSBAR = BOTTOMSTATUSBAR;
int32_t _BOOT_ICON = BOOT_ICON;
int32_t _FRAGBAR = FRAGBAR;
int32_t _JETPACK_ICON = JETPACK_ICON;
int32_t _AIRTANK_ICON = AIRTANK_ICON;
int32_t _STEROIDS_ICON = STEROIDS_ICON;
int32_t _HOLODUKE_ICON = HOLODUKE_ICON;
int32_t _ACCESS_ICON = ACCESS_ICON;
int32_t _DIGITALNUM = DIGITALNUM;
int32_t _DUKECAR = DUKECAR;
int32_t _CAMCORNER = CAMCORNER;
int32_t _CAMLIGHT = CAMLIGHT;
int32_t _LOGO = LOGO;
int32_t _TITLE = TITLE;
int32_t _NUKEWARNINGICON = NUKEWARNINGICON;
int32_t _MOUSECURSOR = MOUSECURSOR;
int32_t _SLIDEBAR = SLIDEBAR;
int32_t _DREALMS = DREALMS;
int32_t _BETASCREEN = BETASCREEN;
int32_t _WINDOWBORDER1 = WINDOWBORDER1;
int32_t _TEXTBOX = TEXTBOX;
int32_t _WINDOWBORDER2 = WINDOWBORDER2;
int32_t _DUKENUKEM = DUKENUKEM;
int32_t _THREEDEE = THREEDEE;
int32_t _INGAMEDUKETHREEDEE = INGAMEDUKETHREEDEE;
int32_t _TENSCREEN = TENSCREEN;
int32_t _PLUTOPAKSPRITE = PLUTOPAKSPRITE;
int32_t _TEATGUN = TEATGUN;
int32_t _KNEE = KNEE;
int32_t _CROSSHAIR = CROSSHAIR;
int32_t _FIRSTGUN = FIRSTGUN;
int32_t _FIRSTGUNRELOAD = FIRSTGUNRELOAD;
int32_t _FALLINGCLIP = FALLINGCLIP;
int32_t _CLIPINHAND = CLIPINHAND;
int32_t _HAND = HAND;
int32_t _SHELL = SHELL;
int32_t _SHOTGUNSHELL = SHOTGUNSHELL;
int32_t _CHAINGUN = CHAINGUN;
int32_t _RPGGUN = RPGGUN;
int32_t _RPGMUZZLEFLASH = RPGMUZZLEFLASH;
int32_t _BUZSAW = BUZSAW;
int32_t _CATLITE = CATLITE;
int32_t _ALIENARMGUN = ALIENARMGUN;
int32_t _HANDHOLDINGLASER = HANDHOLDINGLASER;
int32_t _TRIPBOMB = TRIPBOMB;
int32_t _LASERLINE = LASERLINE;
int32_t _HANDHOLDINGACCESS = HANDHOLDINGACCESS;
int32_t _HANDREMOTE = HANDREMOTE;
int32_t _HANDTHROW = HANDTHROW;
int32_t _TIP = TIP;
int32_t _GLAIR = GLAIR;
int32_t _SCUBAMASK = SCUBAMASK;
int32_t _SPACEMASK = SPACEMASK;
int32_t _FORCESPHERE = FORCESPHERE;
int32_t _SHOTSPARK1 = SHOTSPARK1;
int32_t _RPG = RPG;
int32_t _LASERSITE = LASERSITE;
int32_t _SHOTGUN = SHOTGUN;
int32_t _SPINNINGNUKEICON = SPINNINGNUKEICON;
int32_t _BIGFNTCURSOR = BIGFNTCURSOR;
int32_t _SMALLFNTCURSOR = SMALLFNTCURSOR;
int32_t _STARTALPHANUM = STARTALPHANUM;
int32_t _ENDALPHANUM = ENDALPHANUM;
int32_t _BIGALPHANUM = BIGALPHANUM;
int32_t _BIGPERIOD = BIGPERIOD;
int32_t _BIGCOMMA = BIGCOMMA;
int32_t _BIGX = BIGX;
int32_t _BIGQ = BIGQ;
int32_t _BIGSEMI = BIGSEMI;
int32_t _BIGCOLIN = BIGCOLIN;
int32_t _THREEBYFIVE = THREEBYFIVE;
int32_t _BIGAPPOS = BIGAPPOS;
int32_t __BLANK = BLANK;
int32_t _MINIFONT = MINIFONT;
int32_t _BUTTON1 = BUTTON1;
int32_t _GLASS3 = GLASS3;
int32_t _RESPAWNMARKERRED = RESPAWNMARKERRED;
int32_t _RESPAWNMARKERYELLOW = RESPAWNMARKERYELLOW;
int32_t _RESPAWNMARKERGREEN = RESPAWNMARKERGREEN;
int32_t _BONUSSCREEN = BONUSSCREEN;
int32_t _VIEWBORDER = VIEWBORDER;
int32_t _VICTORY1 = VICTORY1;
int32_t _ORDERING = ORDERING;
int32_t _TEXTSTORY = TEXTSTORY;
int32_t _LOADSCREEN = LOADSCREEN;
int32_t _BORNTOBEWILDSCREEN = BORNTOBEWILDSCREEN;
int32_t _BLIMP = BLIMP;
int32_t _FEM9 = FEM9;
int32_t _FOOTPRINT = FOOTPRINT;
int32_t _FRAMEEFFECT1_13 = FRAMEEFFECT1_13;
int32_t _POOP = POOP;
int32_t _FRAMEEFFECT1 = FRAMEEFFECT1;
int32_t _PANNEL3 = PANNEL3;
int32_t _SCREENBREAK14 = SCREENBREAK14;
int32_t _SCREENBREAK15 = SCREENBREAK15;
int32_t _SCREENBREAK19 = SCREENBREAK19;
int32_t _SCREENBREAK16 = SCREENBREAK16;
int32_t _SCREENBREAK17 = SCREENBREAK17;
int32_t _SCREENBREAK18 = SCREENBREAK18;
int32_t _W_TECHWALL11 = W_TECHWALL11;
int32_t _W_TECHWALL12 = W_TECHWALL12;
int32_t _W_TECHWALL13 = W_TECHWALL13;
int32_t _W_TECHWALL14 = W_TECHWALL14;
int32_t _W_TECHWALL5 = W_TECHWALL5;
int32_t _W_TECHWALL6 = W_TECHWALL6;
int32_t _W_TECHWALL7 = W_TECHWALL7;
int32_t _W_TECHWALL8 = W_TECHWALL8;
int32_t _W_TECHWALL9 = W_TECHWALL9;
int32_t _BPANNEL3 = BPANNEL3;
int32_t _W_HITTECHWALL16 = W_HITTECHWALL16;
int32_t _W_HITTECHWALL10 = W_HITTECHWALL10;
int32_t _W_HITTECHWALL15 = W_HITTECHWALL15;
int32_t _W_MILKSHELF = W_MILKSHELF;
int32_t _W_MILKSHELFBROKE = W_MILKSHELFBROKE;
int32_t _PURPLELAVA = PURPLELAVA;
int32_t _LAVABUBBLE = LAVABUBBLE;
int32_t _DUKECUTOUT = DUKECUTOUT;
int32_t _TARGET = TARGET;
int32_t _GUNPOWDERBARREL = GUNPOWDERBARREL;
int32_t _DUCK = DUCK;
int32_t _HATRACK = HATRACK;
int32_t _DESKLAMP = DESKLAMP;
int32_t _COFFEEMACHINE = COFFEEMACHINE;
int32_t _CUPS = CUPS;
int32_t _GAVALS = GAVALS;
int32_t _GAVALS2 = GAVALS2;
int32_t _POLICELIGHTPOLE = POLICELIGHTPOLE;
int32_t _FLOORBASKET = FLOORBASKET;
int32_t _PUKE = PUKE;
int32_t _DOORTILE23 = DOORTILE23;
int32_t _TOPSECRET = TOPSECRET;
int32_t _SPEAKER = SPEAKER;
int32_t _TEDDYBEAR = TEDDYBEAR;
int32_t _ROBOTDOG = ROBOTDOG;
int32_t _ROBOTPIRATE = ROBOTPIRATE;
int32_t _ROBOTMOUSE = ROBOTMOUSE;
int32_t _MAIL = MAIL;
int32_t _MAILBAG = MAILBAG;
int32_t _HOTMEAT = HOTMEAT;
int32_t _COFFEEMUG = COFFEEMUG;
int32_t _DONUTS2 = DONUTS2;
int32_t _TRIPODCAMERA = TRIPODCAMERA;
int32_t _METER = METER;
int32_t _DESKPHONE = DESKPHONE;
int32_t _GUMBALLMACHINE = GUMBALLMACHINE;
int32_t _GUMBALLMACHINEBROKE = GUMBALLMACHINEBROKE;
int32_t _PAPER = PAPER;
int32_t _MACE = MACE;
int32_t _GENERICPOLE2 = GENERICPOLE2;
int32_t _XXXSTACY = XXXSTACY;
int32_t _WETFLOOR = WETFLOOR;
int32_t _BROOM = BROOM;
int32_t _MOP = MOP;
int32_t _LETTER = LETTER;
int32_t _PIRATE1A = PIRATE1A;
int32_t _PIRATE4A = PIRATE4A;
int32_t _PIRATE2A = PIRATE2A;
int32_t _PIRATE5A = PIRATE5A;
int32_t _PIRATE3A = PIRATE3A;
int32_t _PIRATE6A = PIRATE6A;
int32_t _PIRATEHALF = PIRATEHALF;
int32_t _CHESTOFGOLD = CHESTOFGOLD;
int32_t _SIDEBOLT1 = SIDEBOLT1;
int32_t _FOODOBJECT1 = FOODOBJECT1;
int32_t _FOODOBJECT2 = FOODOBJECT2;
int32_t _FOODOBJECT3 = FOODOBJECT3;
int32_t _FOODOBJECT4 = FOODOBJECT4;
int32_t _FOODOBJECT5 = FOODOBJECT5;
int32_t _FOODOBJECT6 = FOODOBJECT6;
int32_t _FOODOBJECT7 = FOODOBJECT7;
int32_t _FOODOBJECT8 = FOODOBJECT8;
int32_t _FOODOBJECT9 = FOODOBJECT9;
int32_t _FOODOBJECT10 = FOODOBJECT10;
int32_t _FOODOBJECT11 = FOODOBJECT11;
int32_t _FOODOBJECT12 = FOODOBJECT12;
int32_t _FOODOBJECT13 = FOODOBJECT13;
int32_t _FOODOBJECT14 = FOODOBJECT14;
int32_t _FOODOBJECT15 = FOODOBJECT15;
int32_t _FOODOBJECT16 = FOODOBJECT16;
int32_t _FOODOBJECT17 = FOODOBJECT17;
int32_t _FOODOBJECT18 = FOODOBJECT18;
int32_t _FOODOBJECT19 = FOODOBJECT19;
int32_t _FOODOBJECT20 = FOODOBJECT20;
int32_t _HEADLAMP = HEADLAMP;
int32_t _TAMPON = TAMPON;
int32_t _SKINNEDCHICKEN = SKINNEDCHICKEN;
int32_t _FEATHEREDCHICKEN = FEATHEREDCHICKEN;
int32_t _ROBOTDOG2 = ROBOTDOG2;
int32_t _JOLLYMEAL = JOLLYMEAL;
int32_t _DUKEBURGER = DUKEBURGER;
int32_t _SHOPPINGCART = SHOPPINGCART;
int32_t _CANWITHSOMETHING2 = CANWITHSOMETHING2;
int32_t _CANWITHSOMETHING3 = CANWITHSOMETHING3;
int32_t _CANWITHSOMETHING4 = CANWITHSOMETHING4;
int32_t _SNAKEP = SNAKEP;
int32_t _DOLPHIN1 = DOLPHIN1;
int32_t _DOLPHIN2 = DOLPHIN2;

int32_t _FEM10 = FEM10;
int32_t _TOUGHGAL = TOUGHGAL;
int32_t _MAN = MAN;
int32_t _MAN2 = MAN2;
int32_t _WOMAN = WOMAN;
int32_t _PLEASEWAIT = PLEASEWAIT;
int32_t _NATURALLIGHTNING = NATURALLIGHTNING;
int32_t _WEATHERWARN = WEATHERWARN;
int32_t _DUKETAG = DUKETAG;
int32_t _SIGN1 = SIGN1;
int32_t _SIGN2 = SIGN2;
int32_t _JURYGUY = JURYGUY;
int32_t _RESERVEDSLOT1 = RESERVEDSLOT1;
int32_t _RESERVEDSLOT2 = RESERVEDSLOT2;
int32_t _RESERVEDSLOT3 = RESERVEDSLOT3;
int32_t _RESERVEDSLOT4 = RESERVEDSLOT4;
int32_t _RESERVEDSLOT5 = RESERVEDSLOT5;
int32_t _RESERVEDSLOT6 = RESERVEDSLOT6;
int32_t _RESERVEDSLOT7 = RESERVEDSLOT7;
int32_t _RESERVEDSLOT8 = RESERVEDSLOT8;
int32_t _RESERVEDSLOT9 = RESERVEDSLOT9;
int32_t _RESERVEDSLOT10 = RESERVEDSLOT10;
int32_t _RESERVEDSLOT11 = RESERVEDSLOT11;
int32_t _RESERVEDSLOT12 = RESERVEDSLOT12;


struct dynitem {
    char *s;
    int32_t *v;
    int16_t vstat;
    int16_t val;
};
hashtable_t dynnamesH = {512, NULL};

struct dynitem list[]= {
    {"SECTOREFFECTOR",&_SECTOREFFECTOR,SECTOREFFECTOR__STATIC,SECTOREFFECTOR},
    {"ACTIVATOR",&_ACTIVATOR,ACTIVATOR__STATIC,ACTIVATOR},
    {"TOUCHPLATE",&_TOUCHPLATE,TOUCHPLATE__STATIC,TOUCHPLATE},
    {"ACTIVATORLOCKED",&_ACTIVATORLOCKED,ACTIVATORLOCKED__STATIC,ACTIVATORLOCKED},
    {"DOORLOCK",&_DOORLOCK,DOORLOCK__STATIC,DOORLOCK},
    {"MUSICANDSFX",&_MUSICANDSFX,MUSICANDSFX__STATIC,MUSICANDSFX},
    {"LOCATORS",&_LOCATORS,LOCATORS__STATIC,LOCATORS},
    {"CYCLER",&_CYCLER,CYCLER__STATIC,CYCLER},
    {"MASTERSWITCH",&_MASTERSWITCH,MASTERSWITCH__STATIC,MASTERSWITCH},
    {"RESPAWN",&_RESPAWN,RESPAWN__STATIC,RESPAWN},
    {"GPSPEED",&_GPSPEED,GPSPEED__STATIC,GPSPEED},
    {"FOF",&_FOF,FOF__STATIC,FOF},
    {"ARROW",&_ARROW,ARROW__STATIC,ARROW},
    {"SHADESECTOR",&_SHADESECTOR,SHADESECTOR,SHADESECTOR},
    {"FIRSTGUNSPRITE",&_FIRSTGUNSPRITE,FIRSTGUNSPRITE__STATIC,FIRSTGUNSPRITE},
    {"CHAINGUNSPRITE",&_CHAINGUNSPRITE,CHAINGUNSPRITE__STATIC,CHAINGUNSPRITE},
    {"RPGSPRITE",&_RPGSPRITE,RPGSPRITE__STATIC,RPGSPRITE},
    {"BUZSAWSPRITE",&_BUZSAWSPRITE,BUZSAWSPRITE__STATIC,BUZSAWSPRITE},
    {"ALIENARMGUNSPRITE",&_ALIENARMGUNSPRITE,ALIENARMGUNSPRITE__STATIC,ALIENARMGUNSPRITE},
    {"HEAVYHBOMB",&_HEAVYHBOMB,HEAVYHBOMB__STATIC,HEAVYHBOMB},
    {"POWDERKEGSPRITE",&_POWDERKEGSPRITE,POWDERKEGSPRITE__STATIC,POWDERKEGSPRITE},
    {"SHOTGUNSPRITE",&_SHOTGUNSPRITE,SHOTGUNSPRITE__STATIC,SHOTGUNSPRITE},
    {"TEATGUNSPRITE",&_TEATGUNSPRITE,TEATGUNSPRITE__STATIC,TEATGUNSPRITE},
    {"HEALTHBOX",&_HEALTHBOX,HEALTHBOX__STATIC,HEALTHBOX},
    {"AMMOBOX",&_AMMOBOX,AMMOBOX__STATIC,AMMOBOX},
    {"GROWSPRITEICON",&_GROWSPRITEICON,GROWSPRITEICON__STATIC,GROWSPRITEICON},
    {"INVENTORYBOX",&_INVENTORYBOX,INVENTORYBOX__STATIC,INVENTORYBOX},
    {"BUZSAWAMMO",&_BUZSAWAMMO,BUZSAWAMMO__STATIC,BUZSAWAMMO},
    {"AMMO",&_AMMO,AMMO__STATIC,AMMO},
    {"BATTERYAMMO",&_BATTERYAMMO,BATTERYAMMO__STATIC,BATTERYAMMO},
    {"TEATGUNAMMO",&_TEATGUNAMMO,TEATGUNAMMO__STATIC,TEATGUNAMMO},
    {"RPGAMMO",&_RPGAMMO,RPGAMMO__STATIC,RPGAMMO},
    {"GROWAMMO",&_GROWAMMO,GROWAMMO__STATIC,GROWAMMO},
    {"ALIENBLASTERAMMO",&_ALIENBLASTERAMMO,ALIENBLASTERAMMO__STATIC,ALIENBLASTERAMMO},
    {"HBOMBAMMO",&_HBOMBAMMO,HBOMBAMMO__STATIC,HBOMBAMMO},
    {"AMMOLOTS",&_AMMOLOTS,AMMOLOTS__STATIC,AMMOLOTS},
    {"SHOTGUNAMMO",&_SHOTGUNAMMO,SHOTGUNAMMO__STATIC,SHOTGUNAMMO},
    {"COLA",&_COLA,COLA__STATIC,COLA},
    {"SIXPAK",&_SIXPAK,SIXPAK__STATIC,SIXPAK},
    {"FIRSTAID",&_FIRSTAID,FIRSTAID__STATIC,FIRSTAID},
    {"SHIELD",&_SHIELD,SHIELD__STATIC,SHIELD},
    {"STEROIDS",&_STEROIDS,STEROIDS__STATIC,STEROIDS},
    {"AIRTANK",&_AIRTANK,AIRTANK__STATIC,AIRTANK},
    {"JETPACK",&_JETPACK,JETPACK__STATIC,JETPACK},
    {"HEATSENSOR",&_HEATSENSOR,HEATSENSOR__STATIC,HEATSENSOR},
    {"ACCESSCARD",&_ACCESSCARD,ACCESSCARD__STATIC,ACCESSCARD},
    {"BOOTS",&_BOOTS,BOOTS__STATIC,BOOTS},
    {"MIRRORBROKE",&_MIRRORBROKE,MIRRORBROKE__STATIC,MIRRORBROKE},
    {"CLOUDYOCEAN",&_CLOUDYOCEAN,CLOUDYOCEAN__STATIC,CLOUDYOCEAN},
    {"CLOUDYSKIES",&_CLOUDYSKIES,CLOUDYSKIES__STATIC,CLOUDYSKIES},
    {"MOONSKY1",&_MOONSKY1,MOONSKY1__STATIC,MOONSKY1},
    {"MOONSKY2",&_MOONSKY2,MOONSKY2__STATIC,MOONSKY2},
    {"MOONSKY3",&_MOONSKY3,MOONSKY3__STATIC,MOONSKY3},
    {"MOONSKY4",&_MOONSKY4,MOONSKY4__STATIC,MOONSKY4},
    {"BIGORBIT1",&_BIGORBIT1,BIGORBIT1__STATIC,BIGORBIT1},
    {"BIGORBIT2",&_BIGORBIT2,BIGORBIT2__STATIC,BIGORBIT2},
    {"BIGORBIT3",&_BIGORBIT3,BIGORBIT3__STATIC,BIGORBIT3},
    {"BIGORBIT4",&_BIGORBIT4,BIGORBIT4__STATIC,BIGORBIT4},
    {"BIGORBIT5",&_BIGORBIT5,BIGORBIT5__STATIC,BIGORBIT5},
    {"LA",&_LA,LA__STATIC,LA},
    {"REDSKY1",&_REDSKY1,REDSKY1__STATIC,REDSKY1},
    {"REDSKY2",&_REDSKY2,REDSKY2__STATIC,REDSKY2},
    {"ATOMICHEALTH",&_ATOMICHEALTH,ATOMICHEALTH__STATIC,ATOMICHEALTH},
    {"TECHLIGHT2",&_TECHLIGHT2,TECHLIGHT2__STATIC,TECHLIGHT2},
    {"TECHLIGHTBUST2",&_TECHLIGHTBUST2,TECHLIGHTBUST2__STATIC,TECHLIGHTBUST2},
    {"TECHLIGHT4",&_TECHLIGHT4,TECHLIGHT4__STATIC,TECHLIGHT4},
    {"TECHLIGHTBUST4",&_TECHLIGHTBUST4,TECHLIGHTBUST4__STATIC,TECHLIGHTBUST4},
    {"WALLLIGHT4",&_WALLLIGHT4,WALLLIGHT4__STATIC,WALLLIGHT4},
    {"WALLLIGHTBUST4",&_WALLLIGHTBUST4,WALLLIGHTBUST4__STATIC,WALLLIGHTBUST4},
    {"ACCESSSWITCH",&_ACCESSSWITCH,ACCESSSWITCH__STATIC,ACCESSSWITCH},
    {"SLOTDOOR",&_SLOTDOOR,SLOTDOOR__STATIC,SLOTDOOR},
    {"LIGHTSWITCH",&_LIGHTSWITCH,LIGHTSWITCH__STATIC,LIGHTSWITCH},
    {"SPACEDOORSWITCH",&_SPACEDOORSWITCH,SPACEDOORSWITCH__STATIC,SPACEDOORSWITCH},
    {"SPACELIGHTSWITCH",&_SPACELIGHTSWITCH,SPACELIGHTSWITCH__STATIC,SPACELIGHTSWITCH},
    {"FRANKENSTINESWITCH",&_FRANKENSTINESWITCH,FRANKENSTINESWITCH__STATIC,FRANKENSTINESWITCH},
    {"NUKEBUTTON",&_NUKEBUTTON,NUKEBUTTON__STATIC,NUKEBUTTON},
    {"MULTISWITCH",&_MULTISWITCH,MULTISWITCH__STATIC,MULTISWITCH},
    {"MULTISWITCH2",&_MULTISWITCH2,MULTISWITCH2__STATIC,MULTISWITCH2},
    {"DOORTILE5",&_DOORTILE5,DOORTILE5__STATIC,DOORTILE5},
    {"DOORTILE6",&_DOORTILE6,DOORTILE6__STATIC,DOORTILE6},
    {"DOORTILE1",&_DOORTILE1,DOORTILE1__STATIC,DOORTILE1},
    {"DOORTILE2",&_DOORTILE2,DOORTILE2__STATIC,DOORTILE2},
    {"DOORTILE3",&_DOORTILE3,DOORTILE3__STATIC,DOORTILE3},
    {"DOORTILE4",&_DOORTILE4,DOORTILE4__STATIC,DOORTILE4},
    {"DOORTILE7",&_DOORTILE7,DOORTILE7__STATIC,DOORTILE7},
    {"DOORTILE8",&_DOORTILE8,DOORTILE8__STATIC,DOORTILE8},
    {"DOORTILE9",&_DOORTILE9,DOORTILE9__STATIC,DOORTILE9},
    {"DOORTILE10",&_DOORTILE10,DOORTILE10__STATIC,DOORTILE10},
    {"DOORSHOCK",&_DOORSHOCK,DOORSHOCK__STATIC,DOORSHOCK},
    {"DIPSWITCH",&_DIPSWITCH,DIPSWITCH__STATIC,DIPSWITCH},
    {"DIPSWITCH2",&_DIPSWITCH2,DIPSWITCH2__STATIC,DIPSWITCH2},
    {"TECHSWITCH",&_TECHSWITCH,TECHSWITCH__STATIC,TECHSWITCH},
    {"DIPSWITCH3",&_DIPSWITCH3,DIPSWITCH3__STATIC,DIPSWITCH3},
    {"ACCESSSWITCH2",&_ACCESSSWITCH2,ACCESSSWITCH2__STATIC,ACCESSSWITCH2},
    {"REFLECTWATERTILE",&_REFLECTWATERTILE,REFLECTWATERTILE__STATIC,REFLECTWATERTILE},
    {"FLOORSLIME",&_FLOORSLIME,FLOORSLIME__STATIC,FLOORSLIME},
    {"BIGFORCE",&_BIGFORCE,BIGFORCE__STATIC,BIGFORCE},
    {"EPISODE",&_EPISODE,EPISODE__STATIC,EPISODE},
    {"MASKWALL9",&_MASKWALL9,MASKWALL9__STATIC,MASKWALL9},
    {"W_LIGHT",&_W_LIGHT,W_LIGHT__STATIC,W_LIGHT},
    {"SCREENBREAK1",&_SCREENBREAK1,SCREENBREAK1__STATIC,SCREENBREAK1},
    {"SCREENBREAK2",&_SCREENBREAK2,SCREENBREAK2__STATIC,SCREENBREAK2},
    {"SCREENBREAK3",&_SCREENBREAK3,SCREENBREAK3__STATIC,SCREENBREAK3},
    {"SCREENBREAK4",&_SCREENBREAK4,SCREENBREAK4__STATIC,SCREENBREAK4},
    {"SCREENBREAK5",&_SCREENBREAK5,SCREENBREAK5__STATIC,SCREENBREAK5},
    {"SCREENBREAK6",&_SCREENBREAK6,SCREENBREAK6__STATIC,SCREENBREAK6},
    {"SCREENBREAK7",&_SCREENBREAK7,SCREENBREAK7__STATIC,SCREENBREAK7},
    {"SCREENBREAK8",&_SCREENBREAK8,SCREENBREAK8__STATIC,SCREENBREAK8},
    {"SCREENBREAK9",&_SCREENBREAK9,SCREENBREAK9__STATIC,SCREENBREAK9},
    {"SCREENBREAK10",&_SCREENBREAK10,SCREENBREAK10__STATIC,SCREENBREAK10},
    {"SCREENBREAK11",&_SCREENBREAK11,SCREENBREAK11__STATIC,SCREENBREAK11},
    {"SCREENBREAK12",&_SCREENBREAK12,SCREENBREAK12__STATIC,SCREENBREAK12},
    {"SCREENBREAK13",&_SCREENBREAK13,SCREENBREAK13__STATIC,SCREENBREAK13},
    {"MASKWALL1",&_MASKWALL1,MASKWALL1__STATIC,MASKWALL1},
    {"W_TECHWALL1",&_W_TECHWALL1,W_TECHWALL1__STATIC,W_TECHWALL1},
    {"W_TECHWALL2",&_W_TECHWALL2,W_TECHWALL2__STATIC,W_TECHWALL2},
    {"W_TECHWALL15",&_W_TECHWALL15,W_TECHWALL15__STATIC,W_TECHWALL15},
    {"W_TECHWALL3",&_W_TECHWALL3,W_TECHWALL3__STATIC,W_TECHWALL3},
    {"W_TECHWALL4",&_W_TECHWALL4,W_TECHWALL4__STATIC,W_TECHWALL4},
    {"W_TECHWALL10",&_W_TECHWALL10,W_TECHWALL10__STATIC,W_TECHWALL10},
    {"W_TECHWALL16",&_W_TECHWALL16,W_TECHWALL16__STATIC,W_TECHWALL16},
    {"WATERTILE2",&_WATERTILE2,WATERTILE2__STATIC,WATERTILE2},
    {"BPANNEL1",&_BPANNEL1,BPANNEL1__STATIC,BPANNEL1},
    {"PANNEL1",&_PANNEL1,PANNEL1__STATIC,PANNEL1},
    {"PANNEL2",&_PANNEL2,PANNEL2__STATIC,PANNEL2},
    {"WATERTILE",&_WATERTILE,WATERTILE__STATIC,WATERTILE},
    {"STATIC",&_STATIC,STATIC__STATIC,STATIC},
    {"W_SCREENBREAK",&_W_SCREENBREAK,W_SCREENBREAK__STATIC,W_SCREENBREAK},
    {"W_HITTECHWALL3",&_W_HITTECHWALL3,W_HITTECHWALL3__STATIC,W_HITTECHWALL3},
    {"W_HITTECHWALL4",&_W_HITTECHWALL4,W_HITTECHWALL4__STATIC,W_HITTECHWALL4},
    {"W_HITTECHWALL2",&_W_HITTECHWALL2,W_HITTECHWALL2__STATIC,W_HITTECHWALL2},
    {"W_HITTECHWALL1",&_W_HITTECHWALL1,W_HITTECHWALL1__STATIC,W_HITTECHWALL1},
    {"MASKWALL10",&_MASKWALL10,MASKWALL10__STATIC,MASKWALL10},
    {"MASKWALL11",&_MASKWALL11,MASKWALL11__STATIC,MASKWALL11},
    {"DOORTILE22",&_DOORTILE22,DOORTILE22__STATIC,DOORTILE22},
    {"FANSPRITE",&_FANSPRITE,FANSPRITE__STATIC,FANSPRITE},
    {"FANSPRITEBROKE",&_FANSPRITEBROKE,FANSPRITEBROKE__STATIC,FANSPRITEBROKE},
    {"FANSHADOW",&_FANSHADOW,FANSHADOW__STATIC,FANSHADOW},
    {"FANSHADOWBROKE",&_FANSHADOWBROKE,FANSHADOWBROKE__STATIC,FANSHADOWBROKE},
    {"DOORTILE18",&_DOORTILE18,DOORTILE18__STATIC,DOORTILE18},
    {"DOORTILE19",&_DOORTILE19,DOORTILE19__STATIC,DOORTILE19},
    {"DOORTILE20",&_DOORTILE20,DOORTILE20__STATIC,DOORTILE20},
    {"SATELLITE",&_SATELLITE,SATELLITE__STATIC,SATELLITE},
    {"VIEWSCREEN2",&_VIEWSCREEN2,VIEWSCREEN2__STATIC,VIEWSCREEN2},
    {"VIEWSCREENBROKE",&_VIEWSCREENBROKE,VIEWSCREENBROKE__STATIC,VIEWSCREENBROKE},
    {"VIEWSCREEN",&_VIEWSCREEN,VIEWSCREEN__STATIC,VIEWSCREEN},
    {"GLASS",&_GLASS,GLASS__STATIC,GLASS},
    {"GLASS2",&_GLASS2,GLASS2__STATIC,GLASS2},
    {"STAINGLASS1",&_STAINGLASS1,STAINGLASS1__STATIC,STAINGLASS1},
    {"MASKWALL5",&_MASKWALL5,MASKWALL5__STATIC,MASKWALL5},
    {"SATELITE",&_SATELITE,SATELITE__STATIC,SATELITE},
    {"FUELPOD",&_FUELPOD,FUELPOD__STATIC,FUELPOD},
    {"SLIMEPIPE",&_SLIMEPIPE,SLIMEPIPE__STATIC,SLIMEPIPE},
    {"CRACK1",&_CRACK1,CRACK1__STATIC,CRACK1},
    {"CRACK2",&_CRACK2,CRACK2__STATIC,CRACK2},
    {"CRACK3",&_CRACK3,CRACK3__STATIC,CRACK3},
    {"CRACK4",&_CRACK4,CRACK4__STATIC,CRACK4},
    {"FOOTPRINTS",&_FOOTPRINTS,FOOTPRINTS__STATIC,FOOTPRINTS},
    {"DOMELITE",&_DOMELITE,DOMELITE__STATIC,DOMELITE},
    {"CAMERAPOLE",&_CAMERAPOLE,CAMERAPOLE__STATIC,CAMERAPOLE},
    {"CHAIR1",&_CHAIR1,CHAIR1__STATIC,CHAIR1},
    {"CHAIR2",&_CHAIR2,CHAIR2__STATIC,CHAIR2},
    {"BROKENCHAIR",&_BROKENCHAIR,BROKENCHAIR__STATIC,BROKENCHAIR},
    {"MIRROR",&_MIRROR,MIRROR__STATIC,MIRROR},
    {"WATERFOUNTAIN",&_WATERFOUNTAIN,WATERFOUNTAIN__STATIC,WATERFOUNTAIN},
    {"WATERFOUNTAINBROKE",&_WATERFOUNTAINBROKE,WATERFOUNTAINBROKE__STATIC,WATERFOUNTAINBROKE},
    {"FEMMAG1",&_FEMMAG1,FEMMAG1__STATIC,FEMMAG1},
    {"TOILET",&_TOILET,TOILET__STATIC,TOILET},
    {"STALL",&_STALL,STALL__STATIC,STALL},
    {"STALLBROKE",&_STALLBROKE,STALLBROKE__STATIC,STALLBROKE},
    {"FEMMAG2",&_FEMMAG2,FEMMAG2__STATIC,FEMMAG2},
    {"REACTOR2",&_REACTOR2,REACTOR2__STATIC,REACTOR2},
    {"REACTOR2BURNT",&_REACTOR2BURNT,REACTOR2BURNT__STATIC,REACTOR2BURNT},
    {"REACTOR2SPARK",&_REACTOR2SPARK,REACTOR2SPARK__STATIC,REACTOR2SPARK},
    {"GRATE1",&_GRATE1,GRATE1__STATIC,GRATE1},
    {"BGRATE1",&_BGRATE1,BGRATE1__STATIC,BGRATE1},
    {"SOLARPANNEL",&_SOLARPANNEL,SOLARPANNEL__STATIC,SOLARPANNEL},
    {"NAKED1",&_NAKED1,NAKED1__STATIC,NAKED1},
    {"ANTENNA",&_ANTENNA,ANTENNA__STATIC,ANTENNA},
    {"MASKWALL12",&_MASKWALL12,MASKWALL12__STATIC,MASKWALL12},
    {"TOILETBROKE",&_TOILETBROKE,TOILETBROKE__STATIC,TOILETBROKE},
    {"PIPE2",&_PIPE2,PIPE2__STATIC,PIPE2},
    {"PIPE1B",&_PIPE1B,PIPE1B__STATIC,PIPE1B},
    {"PIPE3",&_PIPE3,PIPE3__STATIC,PIPE3},
    {"PIPE1",&_PIPE1,PIPE1__STATIC,PIPE1},
    {"CAMERA1",&_CAMERA1,CAMERA1__STATIC,CAMERA1},
    {"BRICK",&_BRICK,BRICK__STATIC,BRICK},
    {"SPLINTERWOOD",&_SPLINTERWOOD,SPLINTERWOOD__STATIC,SPLINTERWOOD},
    {"PIPE2B",&_PIPE2B,PIPE2B__STATIC,PIPE2B},
    {"BOLT1",&_BOLT1,BOLT1__STATIC,BOLT1},
    {"W_NUMBERS",&_W_NUMBERS,W_NUMBERS__STATIC,W_NUMBERS},
    {"WATERDRIP",&_WATERDRIP,WATERDRIP__STATIC,WATERDRIP},
    {"WATERBUBBLE",&_WATERBUBBLE,WATERBUBBLE__STATIC,WATERBUBBLE},
    {"WATERBUBBLEMAKER",&_WATERBUBBLEMAKER,WATERBUBBLEMAKER__STATIC,WATERBUBBLEMAKER},
    {"W_FORCEFIELD",&_W_FORCEFIELD,W_FORCEFIELD__STATIC,W_FORCEFIELD},
    {"VACUUM",&_VACUUM,VACUUM__STATIC,VACUUM},
    {"FOOTPRINTS2",&_FOOTPRINTS2,FOOTPRINTS2__STATIC,FOOTPRINTS2},
    {"FOOTPRINTS3",&_FOOTPRINTS3,FOOTPRINTS3__STATIC,FOOTPRINTS3},
    {"FOOTPRINTS4",&_FOOTPRINTS4,FOOTPRINTS4__STATIC,FOOTPRINTS4},
    {"EGG",&_EGG,EGG__STATIC,EGG},
    {"SCALE",&_SCALE,SCALE__STATIC,SCALE},
    {"CHAIR3",&_CHAIR3,CHAIR3__STATIC,CHAIR3},
    {"CAMERALIGHT",&_CAMERALIGHT,CAMERALIGHT__STATIC,CAMERALIGHT},
    {"MOVIECAMERA",&_MOVIECAMERA,MOVIECAMERA__STATIC,MOVIECAMERA},
    {"IVUNIT",&_IVUNIT,IVUNIT__STATIC,IVUNIT},
    {"POT1",&_POT1,POT1__STATIC,POT1},
    {"POT2",&_POT2,POT2__STATIC,POT2},
    {"POT3",&_POT3,POT3__STATIC,POT3},
    {"PIPE3B",&_PIPE3B,PIPE3B__STATIC,PIPE3B},
    {"WALLLIGHT3",&_WALLLIGHT3,WALLLIGHT3__STATIC,WALLLIGHT3},
    {"WALLLIGHTBUST3",&_WALLLIGHTBUST3,WALLLIGHTBUST3__STATIC,WALLLIGHTBUST3},
    {"WALLLIGHT1",&_WALLLIGHT1,WALLLIGHT1__STATIC,WALLLIGHT1},
    {"WALLLIGHTBUST1",&_WALLLIGHTBUST1,WALLLIGHTBUST1__STATIC,WALLLIGHTBUST1},
    {"WALLLIGHT2",&_WALLLIGHT2,WALLLIGHT2__STATIC,WALLLIGHT2},
    {"WALLLIGHTBUST2",&_WALLLIGHTBUST2,WALLLIGHTBUST2__STATIC,WALLLIGHTBUST2},
    {"LIGHTSWITCH2",&_LIGHTSWITCH2,LIGHTSWITCH2__STATIC,LIGHTSWITCH2},
    {"WAITTOBESEATED",&_WAITTOBESEATED,WAITTOBESEATED__STATIC,WAITTOBESEATED},
    {"DOORTILE14",&_DOORTILE14,DOORTILE14__STATIC,DOORTILE14},
    {"STATUE",&_STATUE,STATUE__STATIC,STATUE},
    {"MIKE",&_MIKE,MIKE__STATIC,MIKE},
    {"VASE",&_VASE,VASE__STATIC,VASE},
    {"SUSHIPLATE1",&_SUSHIPLATE1,SUSHIPLATE1__STATIC,SUSHIPLATE1},
    {"SUSHIPLATE2",&_SUSHIPLATE2,SUSHIPLATE2__STATIC,SUSHIPLATE2},
    {"SUSHIPLATE3",&_SUSHIPLATE3,SUSHIPLATE3__STATIC,SUSHIPLATE3},
    {"SUSHIPLATE4",&_SUSHIPLATE4,SUSHIPLATE4__STATIC,SUSHIPLATE4},
    {"DOORTILE16",&_DOORTILE16,DOORTILE16__STATIC,DOORTILE16},
    {"SUSHIPLATE5",&_SUSHIPLATE5,SUSHIPLATE5__STATIC,SUSHIPLATE5},
    {"OJ",&_OJ,OJ__STATIC,OJ},
    {"MASKWALL13",&_MASKWALL13,MASKWALL13__STATIC,MASKWALL13},
    {"HURTRAIL",&_HURTRAIL,HURTRAIL__STATIC,HURTRAIL},
    {"POWERSWITCH1",&_POWERSWITCH1,POWERSWITCH1__STATIC,POWERSWITCH1},
    {"LOCKSWITCH1",&_LOCKSWITCH1,LOCKSWITCH1__STATIC,LOCKSWITCH1},
    {"POWERSWITCH2",&_POWERSWITCH2,POWERSWITCH2__STATIC,POWERSWITCH2},
    {"ATM",&_ATM,ATM__STATIC,ATM},
    {"STATUEFLASH",&_STATUEFLASH,STATUEFLASH__STATIC,STATUEFLASH},
    {"ATMBROKE",&_ATMBROKE,ATMBROKE__STATIC,ATMBROKE},
    {"BIGHOLE2",&_BIGHOLE2,BIGHOLE2__STATIC,BIGHOLE2},
    {"STRIPEBALL",&_STRIPEBALL,STRIPEBALL__STATIC,STRIPEBALL},
    {"QUEBALL",&_QUEBALL,QUEBALL__STATIC,QUEBALL},
    {"POCKET",&_POCKET,POCKET__STATIC,POCKET},
    {"WOODENHORSE",&_WOODENHORSE,WOODENHORSE__STATIC,WOODENHORSE},
    {"TREE1",&_TREE1,TREE1__STATIC,TREE1},
    {"TREE2",&_TREE2,TREE2__STATIC,TREE2},
    {"CACTUS",&_CACTUS,CACTUS__STATIC,CACTUS},
    {"MASKWALL2",&_MASKWALL2,MASKWALL2__STATIC,MASKWALL2},
    {"MASKWALL3",&_MASKWALL3,MASKWALL3__STATIC,MASKWALL3},
    {"MASKWALL4",&_MASKWALL4,MASKWALL4__STATIC,MASKWALL4},
    {"FIREEXT",&_FIREEXT,FIREEXT__STATIC,FIREEXT},
    {"TOILETWATER",&_TOILETWATER,TOILETWATER__STATIC,TOILETWATER},
    {"NEON1",&_NEON1,NEON1__STATIC,NEON1},
    {"NEON2",&_NEON2,NEON2__STATIC,NEON2},
    {"CACTUSBROKE",&_CACTUSBROKE,CACTUSBROKE__STATIC,CACTUSBROKE},
    {"BOUNCEMINE",&_BOUNCEMINE,BOUNCEMINE__STATIC,BOUNCEMINE},
    {"BROKEFIREHYDRENT",&_BROKEFIREHYDRENT,BROKEFIREHYDRENT__STATIC,BROKEFIREHYDRENT},
    {"BOX",&_BOX,BOX__STATIC,BOX},
    {"BULLETHOLE",&_BULLETHOLE,BULLETHOLE__STATIC,BULLETHOLE},
    {"BOTTLE1",&_BOTTLE1,BOTTLE1__STATIC,BOTTLE1},
    {"BOTTLE2",&_BOTTLE2,BOTTLE2__STATIC,BOTTLE2},
    {"BOTTLE3",&_BOTTLE3,BOTTLE3__STATIC,BOTTLE3},
    {"BOTTLE4",&_BOTTLE4,BOTTLE4__STATIC,BOTTLE4},
    {"FEMPIC5",&_FEMPIC5,FEMPIC5__STATIC,FEMPIC5},
    {"FEMPIC6",&_FEMPIC6,FEMPIC6__STATIC,FEMPIC6},
    {"FEMPIC7",&_FEMPIC7,FEMPIC7__STATIC,FEMPIC7},
    {"HYDROPLANT",&_HYDROPLANT,HYDROPLANT__STATIC,HYDROPLANT},
    {"OCEANSPRITE1",&_OCEANSPRITE1,OCEANSPRITE1__STATIC,OCEANSPRITE1},
    {"OCEANSPRITE2",&_OCEANSPRITE2,OCEANSPRITE2__STATIC,OCEANSPRITE2},
    {"OCEANSPRITE3",&_OCEANSPRITE3,OCEANSPRITE3__STATIC,OCEANSPRITE3},
    {"OCEANSPRITE4",&_OCEANSPRITE4,OCEANSPRITE4__STATIC,OCEANSPRITE4},
    {"OCEANSPRITE5",&_OCEANSPRITE5,OCEANSPRITE5__STATIC,OCEANSPRITE5},
    {"GENERICPOLE",&_GENERICPOLE,GENERICPOLE__STATIC,GENERICPOLE},
    {"CONE",&_CONE,CONE__STATIC,CONE},
    {"HANGLIGHT",&_HANGLIGHT,HANGLIGHT__STATIC,HANGLIGHT},
    {"HYDRENT",&_HYDRENT,HYDRENT__STATIC,HYDRENT},
    {"MASKWALL14",&_MASKWALL14,MASKWALL14__STATIC,MASKWALL14},
    {"TIRE",&_TIRE,TIRE__STATIC,TIRE},
    {"PIPE5",&_PIPE5,PIPE5__STATIC,PIPE5},
    {"PIPE6",&_PIPE6,PIPE6__STATIC,PIPE6},
    {"PIPE4",&_PIPE4,PIPE4__STATIC,PIPE4},
    {"PIPE4B",&_PIPE4B,PIPE4B__STATIC,PIPE4B},
    {"BROKEHYDROPLANT",&_BROKEHYDROPLANT,BROKEHYDROPLANT__STATIC,BROKEHYDROPLANT},
    {"PIPE5B",&_PIPE5B,PIPE5B__STATIC,PIPE5B},
    {"NEON3",&_NEON3,NEON3__STATIC,NEON3},
    {"NEON4",&_NEON4,NEON4__STATIC,NEON4},
    {"NEON5",&_NEON5,NEON5__STATIC,NEON5},
    {"BOTTLE5",&_BOTTLE5,BOTTLE5__STATIC,BOTTLE5},
    {"BOTTLE6",&_BOTTLE6,BOTTLE6__STATIC,BOTTLE6},
    {"BOTTLE8",&_BOTTLE8,BOTTLE8__STATIC,BOTTLE8},
    {"SPOTLITE",&_SPOTLITE,SPOTLITE__STATIC,SPOTLITE},
    {"HANGOOZ",&_HANGOOZ,HANGOOZ__STATIC,HANGOOZ},
    {"MASKWALL15",&_MASKWALL15,MASKWALL15__STATIC,MASKWALL15},
    {"BOTTLE7",&_BOTTLE7,BOTTLE7__STATIC,BOTTLE7},
    {"HORSEONSIDE",&_HORSEONSIDE,HORSEONSIDE__STATIC,HORSEONSIDE},
    {"GLASSPIECES",&_GLASSPIECES,GLASSPIECES__STATIC,GLASSPIECES},
    {"HORSELITE",&_HORSELITE,HORSELITE__STATIC,HORSELITE},
    {"DONUTS",&_DONUTS,DONUTS__STATIC,DONUTS},
    {"NEON6",&_NEON6,NEON6__STATIC,NEON6},
    {"MASKWALL6",&_MASKWALL6,MASKWALL6__STATIC,MASKWALL6},
    {"CLOCK",&_CLOCK,CLOCK__STATIC,CLOCK},
    {"RUBBERCAN",&_RUBBERCAN,RUBBERCAN__STATIC,RUBBERCAN},
    {"BROKENCLOCK",&_BROKENCLOCK,BROKENCLOCK__STATIC,BROKENCLOCK},
    {"PLUG",&_PLUG,PLUG__STATIC,PLUG},
    {"OOZFILTER",&_OOZFILTER,OOZFILTER__STATIC,OOZFILTER},
    {"FLOORPLASMA",&_FLOORPLASMA,FLOORPLASMA__STATIC,FLOORPLASMA},
    {"REACTOR",&_REACTOR,REACTOR__STATIC,REACTOR},
    {"REACTORSPARK",&_REACTORSPARK,REACTORSPARK__STATIC,REACTORSPARK},
    {"REACTORBURNT",&_REACTORBURNT,REACTORBURNT__STATIC,REACTORBURNT},
    {"DOORTILE15",&_DOORTILE15,DOORTILE15__STATIC,DOORTILE15},
    {"HANDSWITCH",&_HANDSWITCH,HANDSWITCH__STATIC,HANDSWITCH},
    {"CIRCLEPANNEL",&_CIRCLEPANNEL,CIRCLEPANNEL__STATIC,CIRCLEPANNEL},
    {"CIRCLEPANNELBROKE",&_CIRCLEPANNELBROKE,CIRCLEPANNELBROKE__STATIC,CIRCLEPANNELBROKE},
    {"PULLSWITCH",&_PULLSWITCH,PULLSWITCH__STATIC,PULLSWITCH},
    {"MASKWALL8",&_MASKWALL8,MASKWALL8__STATIC,MASKWALL8},
    {"BIGHOLE",&_BIGHOLE,BIGHOLE__STATIC,BIGHOLE},
    {"ALIENSWITCH",&_ALIENSWITCH,ALIENSWITCH__STATIC,ALIENSWITCH},
    {"DOORTILE21",&_DOORTILE21,DOORTILE21__STATIC,DOORTILE21},
    {"HANDPRINTSWITCH",&_HANDPRINTSWITCH,HANDPRINTSWITCH__STATIC,HANDPRINTSWITCH},
    {"BOTTLE10",&_BOTTLE10,BOTTLE10__STATIC,BOTTLE10},
    {"BOTTLE11",&_BOTTLE11,BOTTLE11__STATIC,BOTTLE11},
    {"BOTTLE12",&_BOTTLE12,BOTTLE12__STATIC,BOTTLE12},
    {"BOTTLE13",&_BOTTLE13,BOTTLE13__STATIC,BOTTLE13},
    {"BOTTLE14",&_BOTTLE14,BOTTLE14__STATIC,BOTTLE14},
    {"BOTTLE15",&_BOTTLE15,BOTTLE15__STATIC,BOTTLE15},
    {"BOTTLE16",&_BOTTLE16,BOTTLE16__STATIC,BOTTLE16},
    {"BOTTLE17",&_BOTTLE17,BOTTLE17__STATIC,BOTTLE17},
    {"BOTTLE18",&_BOTTLE18,BOTTLE18__STATIC,BOTTLE18},
    {"BOTTLE19",&_BOTTLE19,BOTTLE19__STATIC,BOTTLE19},
    {"DOORTILE17",&_DOORTILE17,DOORTILE17__STATIC,DOORTILE17},
    {"MASKWALL7",&_MASKWALL7,MASKWALL7__STATIC,MASKWALL7},
    {"JAILBARBREAK",&_JAILBARBREAK,JAILBARBREAK__STATIC,JAILBARBREAK},
    {"DOORTILE11",&_DOORTILE11,DOORTILE11__STATIC,DOORTILE11},
    {"DOORTILE12",&_DOORTILE12,DOORTILE12__STATIC,DOORTILE12},
    {"VENDMACHINE",&_VENDMACHINE,VENDMACHINE__STATIC,VENDMACHINE},
    {"VENDMACHINEBROKE",&_VENDMACHINEBROKE,VENDMACHINEBROKE__STATIC,VENDMACHINEBROKE},
    {"COLAMACHINE",&_COLAMACHINE,COLAMACHINE__STATIC,COLAMACHINE},
    {"COLAMACHINEBROKE",&_COLAMACHINEBROKE,COLAMACHINEBROKE__STATIC,COLAMACHINEBROKE},
    {"CRANEPOLE",&_CRANEPOLE,CRANEPOLE__STATIC,CRANEPOLE},
    {"CRANE",&_CRANE,CRANE__STATIC,CRANE},
    {"BARBROKE",&_BARBROKE,BARBROKE__STATIC,BARBROKE},
    {"BLOODPOOL",&_BLOODPOOL,BLOODPOOL__STATIC,BLOODPOOL},
    {"NUKEBARREL",&_NUKEBARREL,NUKEBARREL__STATIC,NUKEBARREL},
    {"NUKEBARRELDENTED",&_NUKEBARRELDENTED,NUKEBARRELDENTED__STATIC,NUKEBARRELDENTED},
    {"NUKEBARRELLEAKED",&_NUKEBARRELLEAKED,NUKEBARRELLEAKED__STATIC,NUKEBARRELLEAKED},
    {"CANWITHSOMETHING",&_CANWITHSOMETHING,CANWITHSOMETHING__STATIC,CANWITHSOMETHING},
    {"MONEY",&_MONEY,MONEY__STATIC,MONEY},
    {"BANNER",&_BANNER,BANNER__STATIC,BANNER},
    {"EXPLODINGBARREL",&_EXPLODINGBARREL,EXPLODINGBARREL__STATIC,EXPLODINGBARREL},
    {"EXPLODINGBARREL2",&_EXPLODINGBARREL2,EXPLODINGBARREL2__STATIC,EXPLODINGBARREL2},
    {"FIREBARREL",&_FIREBARREL,FIREBARREL__STATIC,FIREBARREL},
    {"SEENINE",&_SEENINE,SEENINE__STATIC,SEENINE},
    {"SEENINEDEAD",&_SEENINEDEAD,SEENINEDEAD__STATIC,SEENINEDEAD},
    {"STEAM",&_STEAM,STEAM__STATIC,STEAM},
    {"CEILINGSTEAM",&_CEILINGSTEAM,CEILINGSTEAM__STATIC,CEILINGSTEAM},
    {"PIPE6B",&_PIPE6B,PIPE6B__STATIC,PIPE6B},
    {"TRANSPORTERBEAM",&_TRANSPORTERBEAM,TRANSPORTERBEAM__STATIC,TRANSPORTERBEAM},
    {"RAT",&_RAT,RAT__STATIC,RAT},
    {"TRASH",&_TRASH,TRASH__STATIC,TRASH},
    {"FEMPIC1",&_FEMPIC1,FEMPIC1__STATIC,FEMPIC1},
    {"FEMPIC2",&_FEMPIC2,FEMPIC2__STATIC,FEMPIC2},
    {"BLANKSCREEN",&_BLANKSCREEN,BLANKSCREEN__STATIC,BLANKSCREEN},
    {"PODFEM1",&_PODFEM1,PODFEM1__STATIC,PODFEM1},
    {"FEMPIC3",&_FEMPIC3,FEMPIC3__STATIC,FEMPIC3},
    {"FEMPIC4",&_FEMPIC4,FEMPIC4__STATIC,FEMPIC4},
    {"FEM1",&_FEM1,FEM1__STATIC,FEM1},
    {"FEM2",&_FEM2,FEM2__STATIC,FEM2},
    {"FEM3",&_FEM3,FEM3__STATIC,FEM3},
    {"FEM5",&_FEM5,FEM5__STATIC,FEM5},
    {"BLOODYPOLE",&_BLOODYPOLE,BLOODYPOLE__STATIC,BLOODYPOLE},
    {"FEM4",&_FEM4,FEM4__STATIC,FEM4},
    {"FEM6",&_FEM6,FEM6__STATIC,FEM6},
    {"FEM6PAD",&_FEM6PAD,FEM6PAD__STATIC,FEM6PAD},
    {"FEM8",&_FEM8,FEM8__STATIC,FEM8},
    {"HELECOPT",&_HELECOPT,HELECOPT__STATIC,HELECOPT},
    {"FETUSJIB",&_FETUSJIB,FETUSJIB__STATIC,FETUSJIB},
    {"HOLODUKE",&_HOLODUKE,HOLODUKE__STATIC,HOLODUKE},
    {"SPACEMARINE",&_SPACEMARINE,SPACEMARINE__STATIC,SPACEMARINE},
    {"INDY",&_INDY,INDY__STATIC,INDY},
    {"FETUS",&_FETUS,FETUS__STATIC,FETUS},
    {"FETUSBROKE",&_FETUSBROKE,FETUSBROKE__STATIC,FETUSBROKE},
    {"MONK",&_MONK,MONK__STATIC,MONK},
    {"LUKE",&_LUKE,LUKE__STATIC,LUKE},
    {"COOLEXPLOSION1",&_COOLEXPLOSION1,COOLEXPLOSION1__STATIC,COOLEXPLOSION1},
    {"WATERSPLASH2",&_WATERSPLASH2,WATERSPLASH2__STATIC,WATERSPLASH2},
    {"FIREVASE",&_FIREVASE,FIREVASE__STATIC,FIREVASE},
    {"SCRATCH",&_SCRATCH,SCRATCH__STATIC,SCRATCH},
    {"FEM7",&_FEM7,FEM7__STATIC,FEM7},
    {"APLAYERTOP",&_APLAYERTOP,APLAYERTOP__STATIC,APLAYERTOP},
    {"APLAYER",&_APLAYER,APLAYER__STATIC,APLAYER},
    {"PLAYERONWATER",&_PLAYERONWATER,PLAYERONWATER__STATIC,PLAYERONWATER},
    {"DUKELYINGDEAD",&_DUKELYINGDEAD,DUKELYINGDEAD__STATIC,DUKELYINGDEAD},
    {"DUKETORSO",&_DUKETORSO,DUKETORSO__STATIC,DUKETORSO},
    {"DUKEGUN",&_DUKEGUN,DUKEGUN__STATIC,DUKEGUN},
    {"DUKELEG",&_DUKELEG,DUKELEG__STATIC,DUKELEG},

    {"BLOOD",&_BLOOD,BLOOD__STATIC,BLOOD},
    {"FIRELASER",&_FIRELASER,FIRELASER__STATIC,FIRELASER},
    {"TRANSPORTERSTAR",&_TRANSPORTERSTAR,TRANSPORTERSTAR__STATIC,TRANSPORTERSTAR},
    {"SPIT",&_SPIT,SPIT__STATIC,SPIT},
    {"LOOGIE",&_LOOGIE,LOOGIE__STATIC,LOOGIE},
    {"FIST",&_FIST,FIST__STATIC,FIST},
    {"CIRCLESAW",&_CIRCLESAW,CIRCLESAW__STATIC,CIRCLESAW},
    {"TEATGUNBLAST",&_TEATGUNBLAST,TEATGUNBLAST__STATIC,TEATGUNBLAST},
    {"TONGUE",&_TONGUE,TONGUE__STATIC,TONGUE},
    {"MORTER",&_MORTER,MORTER__STATIC,MORTER},
    {"ALIENARMGUNEXPLOSION",&_ALIENARMGUNEXPLOSION,ALIENARMGUNEXPLOSION__STATIC,ALIENARMGUNEXPLOSION},
    {"RADIUSEXPLOSION",&_RADIUSEXPLOSION,RADIUSEXPLOSION__STATIC,RADIUSEXPLOSION},
    {"FORCERIPPLE",&_FORCERIPPLE,FORCERIPPLE__STATIC,FORCERIPPLE},

    /*
        {"HEADJIB1",&_HEADJIB1,HEADJIB1__STATIC,HEADJIB1},
        {"ARMJIB1",&_ARMJIB1,ARMJIB1__STATIC,ARMJIB1},
        {"LEGJIB1",&_LEGJIB1,LEGJIB1__STATIC,LEGJIB1},
        {"LIZMANHEAD1",&_LIZMANHEAD1,LIZMANHEAD1__STATIC,LIZMANHEAD1},
        {"LIZMANARM1",&_LIZMANARM1,LIZMANARM1__STATIC,LIZMANARM1},
        {"LIZMANLEG1",&_LIZMANLEG1,LIZMANLEG1__STATIC,LIZMANLEG1},
    /*/
    {"FBOATJIBA", &_FBOATJIBA,FBOATJIBA__STATIC,FBOATJIBA},
    {"FBOATJIBB", &_FBOATJIBB,FBOATJIBB__STATIC,FBOATJIBB},
    {"CHEERJIBA", &_CHEERJIBA,CHEERJIBA__STATIC,CHEERJIBA},
    {"CHEERJIBB", &_CHEERJIBB,CHEERJIBB__STATIC,CHEERJIBB},
    {"CHEERJIBC", &_CHEERJIBC,CHEERJIBC__STATIC,CHEERJIBC},
    {"CHEERJIBD", &_CHEERJIBD,CHEERJIBD__STATIC,CHEERJIBD},
    {"RABBITJIBA", &_RABBITJIBA,RABBITJIBA__STATIC,RABBITJIBA},
    {"RABBITJIBB", &_RABBITJIBB,RABBITJIBB__STATIC,RABBITJIBB},
    {"RABBITJIBC", &_RABBITJIBC,RABBITJIBC__STATIC,RABBITJIBC},
    {"MINJIBA", &_MINJIBA,MINJIBA__STATIC,MINJIBA},
    {"MINJIBB", &_MINJIBB,MINJIBB__STATIC,MINJIBB},
    {"MINJIBC", &_MINJIBC,MINJIBC__STATIC,MINJIBC},
    {"HULKJIBA", &_HULKJIBA,HULKJIBA__STATIC,HULKJIBA},
    {"HULKJIBB", &_HULKJIBB,HULKJIBB__STATIC,HULKJIBB},
    {"HULKJIBC", &_HULKJIBC,HULKJIBC__STATIC,HULKJIBC},
    {"BILLYJIBA", &_BILLYJIBA,BILLYJIBA__STATIC,BILLYJIBA},
    {"BILLYJIBB", &_BILLYJIBB,BILLYJIBB__STATIC,BILLYJIBB},
    {"COOTJIBA", &_COOTJIBA,COOTJIBA__STATIC,COOTJIBA},
    {"COOTJIBB", &_COOTJIBB,COOTJIBB__STATIC,COOTJIBB},
    {"COOTJIBC", &_COOTJIBC,COOTJIBC__STATIC,COOTJIBC},
    {"BIKEJIBA", &_BIKEJIBA,BIKEJIBA__STATIC,BIKEJIBA},
    {"BIKEJIBB", &_BIKEJIBB,BIKEJIBB__STATIC,BIKEJIBB},
    {"BIKEJIBC", &_BIKEJIBC,BIKEJIBC__STATIC,BIKEJIBC},
    {"BIKERJIBA", &_BIKERJIBA,BIKERJIBA__STATIC,BIKERJIBA},
    {"BIKERJIBB", &_BIKERJIBB,BIKERJIBB__STATIC,BIKERJIBB},
    {"BIKERJIBC", &_BIKERJIBC,BIKERJIBC__STATIC,BIKERJIBC},
    {"BIKERJIBD", &_BIKERJIBD,BIKERJIBD__STATIC,BIKERJIBD},
    {"MAMAJIBA", &_MAMAJIBA,MAMAJIBA__STATIC,MAMAJIBA},
    {"MAMAJIBB", &_MAMAJIBB,MAMAJIBB__STATIC,MAMAJIBB},
//*/



    /*
    	{"LIZTROOP",&_LIZTROOP,LIZTROOP__STATIC,LIZTROOP},
        {"LIZTROOPRUNNING",&_LIZTROOPRUNNING,LIZTROOPRUNNING__STATIC,LIZTROOPRUNNING},
        {"LIZTROOPSTAYPUT",&_LIZTROOPSTAYPUT,LIZTROOPSTAYPUT__STATIC,LIZTROOPSTAYPUT},
        {"LIZTOP",&_LIZTOP,LIZTOP__STATIC,LIZTOP},
        {"LIZTROOPSHOOT",&_LIZTROOPSHOOT,LIZTROOPSHOOT__STATIC,LIZTROOPSHOOT},
        {"LIZTROOPJETPACK",&_LIZTROOPJETPACK,LIZTROOPJETPACK__STATIC,LIZTROOPJETPACK},
        {"LIZTROOPDSPRITE",&_LIZTROOPDSPRITE,LIZTROOPDSPRITE__STATIC,LIZTROOPDSPRITE},
        {"LIZTROOPONTOILET",&_LIZTROOPONTOILET,LIZTROOPONTOILET__STATIC,LIZTROOPONTOILET},
        {"LIZTROOPJUSTSIT",&_LIZTROOPJUSTSIT,LIZTROOPJUSTSIT__STATIC,LIZTROOPJUSTSIT},
        {"LIZTROOPDUCKING",&_LIZTROOPDUCKING,LIZTROOPDUCKING__STATIC,LIZTROOPDUCKING},
        {"CANNONBALL",&_CANNONBALL,CANNONBALL__STATIC,CANNONBALL},
        {"OCTABRAIN",&_OCTABRAIN,OCTABRAIN__STATIC,OCTABRAIN},
        {"OCTABRAINSTAYPUT",&_OCTABRAINSTAYPUT,OCTABRAINSTAYPUT__STATIC,OCTABRAINSTAYPUT},
        {"OCTATOP",&_OCTATOP,OCTATOP__STATIC,OCTATOP},
        {"OCTADEADSPRITE",&_OCTADEADSPRITE,OCTADEADSPRITE__STATIC,OCTADEADSPRITE},

        {"DRONE",&_DRONE,DRONE__STATIC,DRONE},

        {"COMMANDER",&_COMMANDER,COMMANDER__STATIC,COMMANDER},
        {"COMMANDERSTAYPUT",&_COMMANDERSTAYPUT,COMMANDERSTAYPUT__STATIC,COMMANDERSTAYPUT},
        {"RECON",&_RECON,RECON__STATIC,RECON},
        {"TANK",&_TANK,TANK__STATIC,TANK},
        {"PIGCOP",&_PIGCOP,PIGCOP__STATIC,PIGCOP},
        {"PIGCOPSTAYPUT",&_PIGCOPSTAYPUT,PIGCOPSTAYPUT__STATIC,PIGCOPSTAYPUT},
        {"PIGCOPDIVE",&_PIGCOPDIVE,PIGCOPDIVE__STATIC,PIGCOPDIVE},
        {"PIGCOPDEADSPRITE",&_PIGCOPDEADSPRITE,PIGCOPDEADSPRITE__STATIC,PIGCOPDEADSPRITE},
        {"PIGTOP",&_PIGTOP,PIGTOP__STATIC,PIGTOP},
        {"LIZMAN",&_LIZMAN,LIZMAN__STATIC,LIZMAN},
        {"LIZMANSTAYPUT",&_LIZMANSTAYPUT,LIZMANSTAYPUT__STATIC,LIZMANSTAYPUT},
        {"LIZMANSPITTING",&_LIZMANSPITTING,LIZMANSPITTING__STATIC,LIZMANSPITTING},
        {"LIZMANFEEDING",&_LIZMANFEEDING,LIZMANFEEDING__STATIC,LIZMANFEEDING},
        {"LIZMANJUMP",&_LIZMANJUMP,LIZMANJUMP__STATIC,LIZMANJUMP},
        {"LIZMANDEADSPRITE",&_LIZMANDEADSPRITE,LIZMANDEADSPRITE__STATIC,LIZMANDEADSPRITE},
        {"FECES",&_FECES,FECES__STATIC,FECES},


    	{"BOSS1",&_BOSS1,BOSS1__STATIC,BOSS1},
        {"BOSS1STAYPUT",&_BOSS1STAYPUT,BOSS1STAYPUT__STATIC,BOSS1STAYPUT},
        {"BOSS1SHOOT",&_BOSS1SHOOT,BOSS1SHOOT__STATIC,BOSS1SHOOT},
        {"BOSS1LOB",&_BOSS1LOB,BOSS1LOB__STATIC,BOSS1LOB},
        {"BOSSTOP",&_BOSSTOP,BOSSTOP__STATIC,BOSSTOP},
        {"BOSS2",&_BOSS2,BOSS2__STATIC,BOSS2},
        {"BOSS3",&_BOSS3,BOSS3__STATIC,BOSS3},

    	{"NEWBEAST",&_NEWBEAST,NEWBEAST__STATIC,NEWBEAST},
        {"NEWBEASTSTAYPUT",&_NEWBEASTSTAYPUT,NEWBEASTSTAYPUT__STATIC,NEWBEASTSTAYPUT},
        {"NEWBEASTJUMP",&_NEWBEASTJUMP,NEWBEASTJUMP__STATIC,NEWBEASTJUMP},
        {"NEWBEASTHANG",&_NEWBEASTHANG,NEWBEASTHANG__STATIC,NEWBEASTHANG},
        {"NEWBEASTHANGDEAD",&_NEWBEASTHANGDEAD,NEWBEASTHANGDEAD__STATIC,NEWBEASTHANGDEAD},
        {"BOSS4",&_BOSS4,BOSS4__STATIC,BOSS4},
        {"BOSS4STAYPUT",&_BOSS4STAYPUT,BOSS4STAYPUT__STATIC,BOSS4STAYPUT},
    /*/
    {"COOT", &_COOT,COOT__STATIC,COOT},
    {"COOTSTAYPUT", &_COOTSTAYPUT,COOTSTAYPUT__STATIC,COOTSTAYPUT},
    {"COOTSHOOT", &_COOTSHOOT,COOTSHOOT__STATIC,COOTSHOOT},
    {"COOTDIE", &_COOTDIE,COOTDIE__STATIC,COOTDIE},
    {"COOTDUCK", &_COOTDUCK,COOTDUCK__STATIC,COOTDUCK},
    {"COOTPAIN", &_COOTPAIN,COOTPAIN__STATIC,COOTPAIN},
    {"COOTTRANS", &_COOTTRANS,COOTTRANS__STATIC,COOTTRANS},
    {"COOTGETUP", &_COOTGETUP,COOTGETUP__STATIC,COOTGETUP},
    {"ECLAIRHEALTH", &_ECLAIRHEALTH,ECLAIRHEALTH__STATIC,ECLAIRHEALTH},
    {"BILLYWALK", &_BILLYWALK,BILLYWALK__STATIC,BILLYWALK},
    {"BILLYDIE", &_BILLYDIE,BILLYDIE__STATIC,BILLYDIE},
    {"BILLYCOCK", &_BILLYCOCK,BILLYCOCK__STATIC,BILLYCOCK},
    {"BILLYRAY", &_BILLYRAY,BILLYRAY__STATIC,BILLYRAY},
    {"BILLYSHOOT", &_BILLYSHOOT,BILLYSHOOT__STATIC,BILLYSHOOT},
    {"BILLYRAYSTAYPUT", &_BILLYRAYSTAYPUT,BILLYRAYSTAYPUT__STATIC,BILLYRAYSTAYPUT},
    {"BILLYBUT", &_BILLYBUT,BILLYBUT__STATIC,BILLYBUT},
    {"BILLYSCRATCH", &_BILLYSCRATCH,BILLYSCRATCH__STATIC,BILLYSCRATCH},
    {"BILLYSNIFF", &_BILLYSNIFF,BILLYSNIFF__STATIC,BILLYSNIFF},
    {"BILLYWOUND", &_BILLYWOUND,BILLYWOUND__STATIC,BILLYWOUND},
    {"BILLYGORE", &_BILLYGORE,BILLYGORE__STATIC,BILLYGORE},
    {"DOGRUN", &_DOGRUN,DOGRUN__STATIC,DOGRUN},
    {"DOGDIE", &_DOGDIE,DOGDIE__STATIC,DOGDIE},
    {"DOGDEAD", &_DOGDEAD,DOGDEAD__STATIC,DOGDEAD},
    {"DOGBARK", &_DOGBARK,DOGBARK__STATIC,DOGBARK},
    {"DOGATTACK", &_DOGATTACK,DOGATTACK__STATIC,DOGATTACK},
    {"LTH", &_LTH,LTH__STATIC,LTH},
    {"LTHSTRAFE", &_LTHSTRAFE,LTHSTRAFE__STATIC,LTHSTRAFE},
    {"LTHLOAD", &_LTHLOAD,LTHLOAD__STATIC,LTHLOAD},
    {"LTHDIE", &_LTHDIE,LTHDIE__STATIC,LTHDIE},
    {"BUBBASCRATCH", &_BUBBASCRATCH,BUBBASCRATCH__STATIC,BUBBASCRATCH},
    {"BUBBANOSE", &_BUBBANOSE,BUBBANOSE__STATIC,BUBBANOSE},
    {"BUBBAPISS", &_BUBBAPISS,BUBBAPISS__STATIC,BUBBAPISS},
    {"BUBBASTAND", &_BUBBASTAND,BUBBASTAND__STATIC,BUBBASTAND},
    {"BUBBAOUCH", &_BUBBAOUCH,BUBBAOUCH__STATIC,BUBBAOUCH},
    {"BUBBADIE", &_BUBBADIE,BUBBADIE__STATIC,BUBBADIE},
    {"BUBBADEAD", &_BUBBADEAD,BUBBADEAD__STATIC,BUBBADEAD},
    {"HULK", &_HULK,HULK__STATIC,HULK},
    {"HULKSTAYPUT", &_HULKSTAYPUT,HULKSTAYPUT__STATIC,HULKSTAYPUT},
    {"HULKA", &_HULKA,HULKA__STATIC,HULKA},
    {"HULKB", &_HULKB,HULKB__STATIC,HULKB},
    {"HULKC", &_HULKC,HULKC__STATIC,HULKC},
    {"SBSWIPE", &_SBSWIPE,SBSWIPE__STATIC,SBSWIPE},
    {"SBPAIN", &_SBPAIN,SBPAIN__STATIC,SBPAIN},
    {"SBDIE", &_SBDIE,SBDIE__STATIC,SBDIE},
    {"HEN", &_HEN,HEN__STATIC,HEN},
    {"HENSTAYPUT", &_HENSTAYPUT,HENSTAYPUT__STATIC,HENSTAYPUT},
    {"HENSTAND", &_HENSTAND,HENSTAND__STATIC,HENSTAND},
    {"MOSQUITO", &_MOSQUITO,MOSQUITO__STATIC,MOSQUITO},
    {"PIG", &_PIG,PIG__STATIC,PIG},
    {"PIGSTAYPUT", &_PIGSTAYPUT,PIGSTAYPUT__STATIC,PIGSTAYPUT},
    {"PIGEAT", &_PIGEAT,PIGEAT__STATIC,PIGEAT},
    {"SBMOVE", &_SBMOVE,SBMOVE__STATIC,SBMOVE},
    {"SBSPIT", &_SBSPIT,SBSPIT__STATIC,SBSPIT},
    {"SBDIP", &_SBDIP,SBDIP__STATIC,SBDIP},
    {"MINION", &_MINION,MINION__STATIC,MINION},
    {"MINIONSTAYPUT", &_MINIONSTAYPUT,MINIONSTAYPUT__STATIC,MINIONSTAYPUT},
    {"UFO1", &_UFO1,UFO1__STATIC,UFO1},
    {"UFO2", &_UFO2,UFO2__STATIC,UFO2},
    {"UFO3", &_UFO3,UFO3__STATIC,UFO3},
    {"UFO4", &_UFO4,UFO4__STATIC,UFO4},
    {"UFO5", &_UFO5,UFO5__STATIC,UFO5},
    {"COW", &_COW,COW__STATIC,COW},
    {"VIXEN", &_VIXEN,VIXEN__STATIC,VIXEN},
    {"VIXENPAIN", &_VIXENPAIN,VIXENPAIN__STATIC,VIXENPAIN},
    {"VIXENDIE", &_VIXENDIE,VIXENDIE__STATIC,VIXENDIE},
    {"VIXENSHOOT", &_VIXENSHOOT,VIXENSHOOT__STATIC,VIXENSHOOT},
    {"VIXENWDN", &_VIXENWDN,VIXENWDN__STATIC,VIXENWDN},
    {"VIXENWUP", &_VIXENWUP,VIXENWUP__STATIC,VIXENWUP},
    {"VIXENKICK", &_VIXENKICK,VIXENKICK__STATIC,VIXENKICK},
    {"VIXENTELE", &_VIXENTELE,VIXENTELE__STATIC,VIXENTELE},
    {"VIXENTEAT", &_VIXENTEAT,VIXENTEAT__STATIC,VIXENTEAT},
    {"MOTOHIT", &_MOTOHIT,MOTOHIT__STATIC,MOTOHIT},
    {"BOATHIT", &_BOATHIT,BOATHIT__STATIC,BOATHIT},
    {"EMPTYBIKE", &_EMPTYBIKE,EMPTYBIKE__STATIC,EMPTYBIKE},
    {"EMPTYBOAT", &_EMPTYBOAT,EMPTYBOAT__STATIC,EMPTYBOAT},
    {"RABBIT", &_RABBIT,RABBIT__STATIC,RABBIT},
    {"MAKEOUT", &_MAKEOUT,MAKEOUT__STATIC,MAKEOUT},
    {"DEADBIKE", &_DEADBIKE,DEADBIKE__STATIC,DEADBIKE},
    {"CHEER", &_CHEER,CHEER__STATIC,CHEER},
    {"CHEERSTAYPUT", &_CHEERSTAYPUT,CHEERSTAYPUT__STATIC,CHEERSTAYPUT},
    {"CHEERB", &_CHEERB,CHEERB__STATIC,CHEERB},
    {"CHEERBOMB", &_CHEERBOMB,CHEERBOMB__STATIC,CHEERBOMB},
    {"CHEERBLADE", &_CHEERBLADE,CHEERBLADE__STATIC,CHEERBLADE},
    {"MOTOGUN", &_MOTOGUN,MOTOGUN__STATIC,MOTOGUN},
    {"MOTOAMMO", &_MOTOAMMO,MOTOAMMO__STATIC,MOTOAMMO},
    {"BOATAMMO", &_BOATAMMO,BOATAMMO__STATIC,BOATAMMO},
    {"WEED", &_WEED,WEED__STATIC,WEED},
    {"BIKERB", &_BIKERB,BIKERB__STATIC,BIKERB},
    {"BIKERBV2", &_BIKERBV2,BIKERBV2__STATIC,BIKERBV2},
    {"BIKER", &_BIKER,BIKER__STATIC,BIKER},
    {"MINIONBOAT", &_MINIONBOAT,MINIONBOAT__STATIC,MINIONBOAT},
    {"HULKBOAT", &_HULKBOAT,HULKBOAT__STATIC,HULKBOAT},
    {"CHEERBOAT", &_CHEERBOAT,CHEERBOAT__STATIC,CHEERBOAT},
    {"MAMA", &_MAMA,MAMA__STATIC,MAMA},
    {"MAMACLOUD", &_MAMACLOUD,MAMACLOUD__STATIC,MAMACLOUD},
    {"COOTPLAY", &_COOTPLAY,COOTPLAY__STATIC,COOTPLAY},
    {"BILLYPLAY", &_BILLYPLAY,BILLYPLAY__STATIC,BILLYPLAY},
//*/
    {"INNERJAW",&_INNERJAW,INNERJAW__STATIC,INNERJAW},
    {"EXPLOSION2",&_EXPLOSION2,EXPLOSION2__STATIC,EXPLOSION2},
    {"EXPLOSION2BOT",&_EXPLOSION2BOT,EXPLOSION2BOT__STATIC,EXPLOSION2BOT},
    {"USERWEAPON",&_USERWEAPON,USERWEAPON__STATIC,USERWEAPON},
    {"HEADERBAR",&_HEADERBAR,HEADERBAR__STATIC,HEADERBAR},
    {"JIBS1",&_JIBS1,JIBS1__STATIC,JIBS1},
    {"JIBS2",&_JIBS2,JIBS2__STATIC,JIBS2},
    {"JIBS3",&_JIBS3,JIBS3__STATIC,JIBS3},
    {"JIBS4",&_JIBS4,JIBS4__STATIC,JIBS4},
    {"JIBS5",&_JIBS5,JIBS5__STATIC,JIBS5},
    {"BURNING",&_BURNING,BURNING__STATIC,BURNING},
    {"FIRE",&_FIRE,FIRE__STATIC,FIRE},
    {"JIBS6",&_JIBS6,JIBS6__STATIC,JIBS6},
    {"BLOODSPLAT1",&_BLOODSPLAT1,BLOODSPLAT1__STATIC,BLOODSPLAT1},
    {"BLOODSPLAT3",&_BLOODSPLAT3,BLOODSPLAT3__STATIC,BLOODSPLAT3},
    {"BLOODSPLAT2",&_BLOODSPLAT2,BLOODSPLAT2__STATIC,BLOODSPLAT2},
    {"BLOODSPLAT4",&_BLOODSPLAT4,BLOODSPLAT4__STATIC,BLOODSPLAT4},
    {"OOZ",&_OOZ,OOZ__STATIC,OOZ},
    {"OOZ2",&_OOZ2,OOZ2__STATIC,OOZ2},
    {"WALLBLOOD1",&_WALLBLOOD1,WALLBLOOD1__STATIC,WALLBLOOD1},
    {"WALLBLOOD2",&_WALLBLOOD2,WALLBLOOD2__STATIC,WALLBLOOD2},
    {"WALLBLOOD3",&_WALLBLOOD3,WALLBLOOD3__STATIC,WALLBLOOD3},
    {"WALLBLOOD4",&_WALLBLOOD4,WALLBLOOD4__STATIC,WALLBLOOD4},
    {"WALLBLOOD5",&_WALLBLOOD5,WALLBLOOD5__STATIC,WALLBLOOD5},
    {"WALLBLOOD6",&_WALLBLOOD6,WALLBLOOD6__STATIC,WALLBLOOD6},
    {"WALLBLOOD7",&_WALLBLOOD7,WALLBLOOD7__STATIC,WALLBLOOD7},
    {"WALLBLOOD8",&_WALLBLOOD8,WALLBLOOD8__STATIC,WALLBLOOD8},
    {"BURNING2",&_BURNING2,BURNING2__STATIC,BURNING2},
    {"FIRE2",&_FIRE2,FIRE2__STATIC,FIRE2},
    {"CRACKKNUCKLES",&_CRACKKNUCKLES,CRACKKNUCKLES__STATIC,CRACKKNUCKLES},
    {"SMALLSMOKE",&_SMALLSMOKE,SMALLSMOKE__STATIC,SMALLSMOKE},
    {"SMALLSMOKEMAKER",&_SMALLSMOKEMAKER,SMALLSMOKEMAKER__STATIC,SMALLSMOKEMAKER},
    {"FLOORFLAME",&_FLOORFLAME,FLOORFLAME__STATIC,FLOORFLAME},
    {"ROTATEGUN",&_ROTATEGUN,ROTATEGUN__STATIC,ROTATEGUN},
    {"GREENSLIME",&_GREENSLIME,GREENSLIME__STATIC,GREENSLIME},
    {"WATERDRIPSPLASH",&_WATERDRIPSPLASH,WATERDRIPSPLASH__STATIC,WATERDRIPSPLASH},
    {"SCRAP6",&_SCRAP6,SCRAP6__STATIC,SCRAP6},
    {"SCRAP1",&_SCRAP1,SCRAP1__STATIC,SCRAP1},
    {"SCRAP2",&_SCRAP2,SCRAP2__STATIC,SCRAP2},
    {"SCRAP3",&_SCRAP3,SCRAP3__STATIC,SCRAP3},
    {"SCRAP4",&_SCRAP4,SCRAP4__STATIC,SCRAP4},
    {"SCRAP5",&_SCRAP5,SCRAP5__STATIC,SCRAP5},

    {"BETAVERSION",&_BETAVERSION,BETAVERSION__STATIC,BETAVERSION},
    {"PLAYERISHERE",&_PLAYERISHERE,PLAYERISHERE__STATIC,PLAYERISHERE},
    {"PLAYERWASHERE",&_PLAYERWASHERE,PLAYERWASHERE__STATIC,PLAYERWASHERE},
    {"SELECTDIR",&_SELECTDIR,SELECTDIR__STATIC,SELECTDIR},
    {"F1HELP",&_F1HELP,F1HELP__STATIC,F1HELP},
    {"NOTCHON",&_NOTCHON,NOTCHON__STATIC,NOTCHON},
    {"NOTCHOFF",&_NOTCHOFF,NOTCHOFF__STATIC,NOTCHOFF},
    {"GROWSPARK",&_GROWSPARK,GROWSPARK__STATIC,GROWSPARK},
    {"DUKEICON",&_DUKEICON,DUKEICON__STATIC,DUKEICON},
    {"BADGUYICON",&_BADGUYICON,BADGUYICON__STATIC,BADGUYICON},
    {"FOODICON",&_FOODICON,FOODICON__STATIC,FOODICON},
    {"GETICON",&_GETICON,GETICON__STATIC,GETICON},
    {"MENUSCREEN",&_MENUSCREEN,MENUSCREEN__STATIC,MENUSCREEN},
    {"MENUBAR",&_MENUBAR,MENUBAR__STATIC,MENUBAR},
    {"KILLSICON",&_KILLSICON,KILLSICON__STATIC,KILLSICON},
    {"FIRSTAID_ICON",&_FIRSTAID_ICON,FIRSTAID_ICON__STATIC,FIRSTAID_ICON},
    {"HEAT_ICON",&_HEAT_ICON,HEAT_ICON__STATIC,HEAT_ICON},
    {"BOTTOMSTATUSBAR",&_BOTTOMSTATUSBAR,BOTTOMSTATUSBAR__STATIC,BOTTOMSTATUSBAR},
    {"BOOT_ICON",&_BOOT_ICON,BOOT_ICON__STATIC,BOOT_ICON},
    {"FRAGBAR",&_FRAGBAR,FRAGBAR__STATIC,FRAGBAR},
    {"JETPACK_ICON",&_JETPACK_ICON,JETPACK_ICON__STATIC,JETPACK_ICON},
    {"AIRTANK_ICON",&_AIRTANK_ICON,AIRTANK_ICON__STATIC,AIRTANK_ICON},
    {"STEROIDS_ICON",&_STEROIDS_ICON,STEROIDS_ICON__STATIC,STEROIDS_ICON},
    {"HOLODUKE_ICON",&_HOLODUKE_ICON,HOLODUKE_ICON__STATIC,HOLODUKE_ICON},
    {"ACCESS_ICON",&_ACCESS_ICON,ACCESS_ICON__STATIC,ACCESS_ICON},
    {"DIGITALNUM",&_DIGITALNUM,DIGITALNUM__STATIC,DIGITALNUM},
    {"DUKECAR",&_DUKECAR,DUKECAR__STATIC,DUKECAR},
    {"CAMCORNER",&_CAMCORNER,CAMCORNER__STATIC,CAMCORNER},
    {"CAMLIGHT",&_CAMLIGHT,CAMLIGHT__STATIC,CAMLIGHT},
    {"LOGO",&_LOGO,LOGO__STATIC,LOGO},
    {"TITLE",&_TITLE,TITLE__STATIC,TITLE},
    {"NUKEWARNINGICON",&_NUKEWARNINGICON,NUKEWARNINGICON__STATIC,NUKEWARNINGICON},
    {"MOUSECURSOR",&_MOUSECURSOR,MOUSECURSOR__STATIC,MOUSECURSOR},
    {"SLIDEBAR",&_SLIDEBAR,SLIDEBAR__STATIC,SLIDEBAR},
    {"DREALMS",&_DREALMS,DREALMS__STATIC,DREALMS},
    {"BETASCREEN",&_BETASCREEN,BETASCREEN__STATIC,BETASCREEN},
    {"WINDOWBORDER1",&_WINDOWBORDER1,WINDOWBORDER1__STATIC,WINDOWBORDER1},
    {"TEXTBOX",&_TEXTBOX,TEXTBOX__STATIC,TEXTBOX},
    {"WINDOWBORDER2",&_WINDOWBORDER2,WINDOWBORDER2__STATIC,WINDOWBORDER2},
    {"DUKENUKEM",&_DUKENUKEM,DUKENUKEM__STATIC,DUKENUKEM},
    {"THREEDEE",&_THREEDEE,THREEDEE__STATIC,THREEDEE},
    {"INGAMEDUKETHREEDEE",&_INGAMEDUKETHREEDEE,INGAMEDUKETHREEDEE__STATIC,INGAMEDUKETHREEDEE},
    {"TENSCREEN",&_TENSCREEN,TENSCREEN__STATIC,TENSCREEN},
    {"PLUTOPAKSPRITE",&_PLUTOPAKSPRITE,PLUTOPAKSPRITE__STATIC,PLUTOPAKSPRITE},
    {"TEATGUN",&_TEATGUN,TEATGUN__STATIC,TEATGUN},
    {"KNEE",&_KNEE,KNEE__STATIC,KNEE},
    {"CROSSHAIR",&_CROSSHAIR,CROSSHAIR__STATIC,CROSSHAIR},
    {"FIRSTGUN",&_FIRSTGUN,FIRSTGUN__STATIC,FIRSTGUN},
    {"FIRSTGUNRELOAD",&_FIRSTGUNRELOAD,FIRSTGUNRELOAD__STATIC,FIRSTGUNRELOAD},
    {"FALLINGCLIP",&_FALLINGCLIP,FALLINGCLIP__STATIC,FALLINGCLIP},
    {"CLIPINHAND",&_CLIPINHAND,CLIPINHAND__STATIC,CLIPINHAND},
    {"HAND",&_HAND,HAND__STATIC,HAND},
    {"SHELL",&_SHELL,SHELL__STATIC,SHELL},
    {"SHOTGUNSHELL",&_SHOTGUNSHELL,SHOTGUNSHELL__STATIC,SHOTGUNSHELL},
    {"CHAINGUN",&_CHAINGUN,CHAINGUN__STATIC,CHAINGUN},
    {"RPGGUN",&_RPGGUN,RPGGUN__STATIC,RPGGUN},
    {"RPGMUZZLEFLASH",&_RPGMUZZLEFLASH,RPGMUZZLEFLASH__STATIC,RPGMUZZLEFLASH},
    {"BUZSAW",&_BUZSAW,BUZSAW__STATIC,BUZSAW},
    {"CATLITE",&_CATLITE,CATLITE__STATIC,CATLITE},
    {"ALIENARMGUN",&_ALIENARMGUN,ALIENARMGUN__STATIC,ALIENARMGUN},
    {"HANDHOLDINGLASER",&_HANDHOLDINGLASER,HANDHOLDINGLASER__STATIC,HANDHOLDINGLASER},
    {"TRIPBOMB",&_TRIPBOMB,TRIPBOMB__STATIC,TRIPBOMB},
    {"LASERLINE",&_LASERLINE,LASERLINE__STATIC,LASERLINE},
    {"HANDHOLDINGACCESS",&_HANDHOLDINGACCESS,HANDHOLDINGACCESS__STATIC,HANDHOLDINGACCESS},
    {"HANDREMOTE",&_HANDREMOTE,HANDREMOTE__STATIC,HANDREMOTE},
    {"HANDTHROW",&_HANDTHROW,HANDTHROW__STATIC,HANDTHROW},
    {"TIP",&_TIP,TIP__STATIC,TIP},
    {"GLAIR",&_GLAIR,GLAIR__STATIC,GLAIR},
    {"SCUBAMASK",&_SCUBAMASK,SCUBAMASK__STATIC,SCUBAMASK},
    {"SPACEMASK",&_SPACEMASK,SPACEMASK__STATIC,SPACEMASK},
    {"FORCESPHERE",&_FORCESPHERE,FORCESPHERE__STATIC,FORCESPHERE},
    {"SHOTSPARK1",&_SHOTSPARK1,SHOTSPARK1__STATIC,SHOTSPARK1},
    {"RPG",&_RPG,RPG__STATIC,RPG},
    {"LASERSITE",&_LASERSITE,LASERSITE__STATIC,LASERSITE},
    {"SHOTGUN",&_SHOTGUN,SHOTGUN__STATIC,SHOTGUN},
    {"SPINNINGNUKEICON",&_SPINNINGNUKEICON,SPINNINGNUKEICON__STATIC,SPINNINGNUKEICON},
    {"BIGFNTCURSOR",&_BIGFNTCURSOR,BIGFNTCURSOR__STATIC,BIGFNTCURSOR},
    {"SMALLFNTCURSOR",&_SMALLFNTCURSOR,SMALLFNTCURSOR__STATIC,SMALLFNTCURSOR},
    {"STARTALPHANUM",&_STARTALPHANUM,STARTALPHANUM__STATIC,STARTALPHANUM},
    {"ENDALPHANUM",&_ENDALPHANUM,ENDALPHANUM__STATIC,ENDALPHANUM},
    {"BIGALPHANUM",&_BIGALPHANUM,BIGALPHANUM__STATIC,BIGALPHANUM},
    {"BIGPERIOD",&_BIGPERIOD,BIGPERIOD__STATIC,BIGPERIOD},
    {"BIGCOMMA",&_BIGCOMMA,BIGCOMMA__STATIC,BIGCOMMA},
    {"BIGX",&_BIGX,BIGX__STATIC,BIGX},
    {"BIGQ",&_BIGQ,BIGQ__STATIC,BIGQ},
    {"BIGSEMI",&_BIGSEMI,BIGSEMI__STATIC,BIGSEMI},
    {"BIGCOLIN",&_BIGCOLIN,BIGCOLIN__STATIC,BIGCOLIN},
    {"THREEBYFIVE",&_THREEBYFIVE,THREEBYFIVE__STATIC,THREEBYFIVE},
    {"BIGAPPOS",&_BIGAPPOS,BIGAPPOS__STATIC,BIGAPPOS},
    {"BLANK",&__BLANK,BLANK__STATIC,BLANK},
    {"MINIFONT",&_MINIFONT,MINIFONT__STATIC,MINIFONT},
    {"BUTTON1",&_BUTTON1,BUTTON1__STATIC,BUTTON1},
    {"GLASS3",&_GLASS3,GLASS3__STATIC,GLASS3},
    {"RESPAWNMARKERRED",&_RESPAWNMARKERRED,RESPAWNMARKERRED__STATIC,RESPAWNMARKERRED},
    {"RESPAWNMARKERYELLOW",&_RESPAWNMARKERYELLOW,RESPAWNMARKERYELLOW__STATIC,RESPAWNMARKERYELLOW},
    {"RESPAWNMARKERGREEN",&_RESPAWNMARKERGREEN,RESPAWNMARKERGREEN__STATIC,RESPAWNMARKERGREEN},
    {"BONUSSCREEN",&_BONUSSCREEN,BONUSSCREEN__STATIC,BONUSSCREEN},
    {"VIEWBORDER",&_VIEWBORDER,VIEWBORDER__STATIC,VIEWBORDER},
    {"VICTORY1",&_VICTORY1,VICTORY1__STATIC,VICTORY1},
    {"ORDERING",&_ORDERING,ORDERING__STATIC,ORDERING},
    {"TEXTSTORY",&_TEXTSTORY,TEXTSTORY__STATIC,TEXTSTORY},
    {"LOADSCREEN",&_LOADSCREEN,LOADSCREEN__STATIC,LOADSCREEN},
    {"BORNTOBEWILDSCREEN",&_BORNTOBEWILDSCREEN,BORNTOBEWILDSCREEN__STATIC,BORNTOBEWILDSCREEN},
    {"BLIMP",&_BLIMP,BLIMP__STATIC,BLIMP},
    {"FEM9",&_FEM9,FEM9__STATIC,FEM9},
    {"FOOTPRINT",&_FOOTPRINT,FOOTPRINT__STATIC,FOOTPRINT},
    {"FRAMEEFFECT1_13",&_FRAMEEFFECT1_13,FRAMEEFFECT1_13__STATIC,FRAMEEFFECT1_13},
    {"POOP",&_POOP,POOP__STATIC,POOP},
    {"FRAMEEFFECT1",&_FRAMEEFFECT1,FRAMEEFFECT1__STATIC,FRAMEEFFECT1},
    {"PANNEL3",&_PANNEL3,PANNEL3__STATIC,PANNEL3},
    {"SCREENBREAK14",&_SCREENBREAK14,SCREENBREAK14__STATIC,SCREENBREAK14},
    {"SCREENBREAK15",&_SCREENBREAK15,SCREENBREAK15__STATIC,SCREENBREAK15},
    {"SCREENBREAK19",&_SCREENBREAK19,SCREENBREAK19__STATIC,SCREENBREAK19},
    {"SCREENBREAK16",&_SCREENBREAK16,SCREENBREAK16__STATIC,SCREENBREAK16},
    {"SCREENBREAK17",&_SCREENBREAK17,SCREENBREAK17__STATIC,SCREENBREAK17},
    {"SCREENBREAK18",&_SCREENBREAK18,SCREENBREAK18__STATIC,SCREENBREAK18},
    {"W_TECHWALL11",&_W_TECHWALL11,W_TECHWALL11__STATIC,W_TECHWALL11},
    {"W_TECHWALL12",&_W_TECHWALL12,W_TECHWALL12__STATIC,W_TECHWALL12},
    {"W_TECHWALL13",&_W_TECHWALL13,W_TECHWALL13__STATIC,W_TECHWALL13},
    {"W_TECHWALL14",&_W_TECHWALL14,W_TECHWALL14__STATIC,W_TECHWALL14},
    {"W_TECHWALL5",&_W_TECHWALL5,W_TECHWALL5__STATIC,W_TECHWALL5},
    {"W_TECHWALL6",&_W_TECHWALL6,W_TECHWALL6__STATIC,W_TECHWALL6},
    {"W_TECHWALL7",&_W_TECHWALL7,W_TECHWALL7__STATIC,W_TECHWALL7},
    {"W_TECHWALL8",&_W_TECHWALL8,W_TECHWALL8__STATIC,W_TECHWALL8},
    {"W_TECHWALL9",&_W_TECHWALL9,W_TECHWALL9__STATIC,W_TECHWALL9},
    {"BPANNEL3",&_BPANNEL3,BPANNEL3__STATIC,BPANNEL3},
    {"W_HITTECHWALL16",&_W_HITTECHWALL16,W_HITTECHWALL16__STATIC,W_HITTECHWALL16},
    {"W_HITTECHWALL10",&_W_HITTECHWALL10,W_HITTECHWALL10__STATIC,W_HITTECHWALL10},
    {"W_HITTECHWALL15",&_W_HITTECHWALL15,W_HITTECHWALL15__STATIC,W_HITTECHWALL15},
    {"W_MILKSHELF",&_W_MILKSHELF,W_MILKSHELF__STATIC,W_MILKSHELF},
    {"W_MILKSHELFBROKE",&_W_MILKSHELFBROKE,W_MILKSHELFBROKE__STATIC,W_MILKSHELFBROKE},
    {"PURPLELAVA",&_PURPLELAVA,PURPLELAVA__STATIC,PURPLELAVA},
    {"LAVABUBBLE",&_LAVABUBBLE,LAVABUBBLE__STATIC,LAVABUBBLE},
    {"DUKECUTOUT",&_DUKECUTOUT,DUKECUTOUT__STATIC,DUKECUTOUT},
    {"TARGET",&_TARGET,TARGET__STATIC,TARGET},
    {"GUNPOWDERBARREL",&_GUNPOWDERBARREL,GUNPOWDERBARREL__STATIC,GUNPOWDERBARREL},
    {"DUCK",&_DUCK,DUCK__STATIC,DUCK},
    {"HATRACK",&_HATRACK,HATRACK__STATIC,HATRACK},
    {"DESKLAMP",&_DESKLAMP,DESKLAMP__STATIC,DESKLAMP},
    {"COFFEEMACHINE",&_COFFEEMACHINE,COFFEEMACHINE__STATIC,COFFEEMACHINE},
    {"CUPS",&_CUPS,CUPS__STATIC,CUPS},
    {"GAVALS",&_GAVALS,GAVALS__STATIC,GAVALS},
    {"GAVALS2",&_GAVALS2,GAVALS2__STATIC,GAVALS2},
    {"POLICELIGHTPOLE",&_POLICELIGHTPOLE,POLICELIGHTPOLE__STATIC,POLICELIGHTPOLE},
    {"FLOORBASKET",&_FLOORBASKET,FLOORBASKET__STATIC,FLOORBASKET},
    {"PUKE",&_PUKE,PUKE__STATIC,PUKE},
    {"DOORTILE23",&_DOORTILE23,DOORTILE23__STATIC,DOORTILE23},
    {"TOPSECRET",&_TOPSECRET,TOPSECRET__STATIC,TOPSECRET},
    {"SPEAKER",&_SPEAKER,SPEAKER__STATIC,SPEAKER},
    {"TEDDYBEAR",&_TEDDYBEAR,TEDDYBEAR__STATIC,TEDDYBEAR},
    {"ROBOTDOG",&_ROBOTDOG,ROBOTDOG__STATIC,ROBOTDOG},
    {"ROBOTPIRATE",&_ROBOTPIRATE,ROBOTPIRATE__STATIC,ROBOTPIRATE},
    {"ROBOTMOUSE",&_ROBOTMOUSE,ROBOTMOUSE__STATIC,ROBOTMOUSE},
    {"MAIL",&_MAIL,MAIL__STATIC,MAIL},
    {"MAILBAG",&_MAILBAG,MAILBAG__STATIC,MAILBAG},
    {"HOTMEAT",&_HOTMEAT,HOTMEAT__STATIC,HOTMEAT},
    {"COFFEEMUG",&_COFFEEMUG,COFFEEMUG__STATIC,COFFEEMUG},
    {"DONUTS2",&_DONUTS2,DONUTS2__STATIC,DONUTS2},
    {"TRIPODCAMERA",&_TRIPODCAMERA,TRIPODCAMERA__STATIC,TRIPODCAMERA},
    {"METER",&_METER,METER__STATIC,METER},
    {"DESKPHONE",&_DESKPHONE,DESKPHONE__STATIC,DESKPHONE},
    {"GUMBALLMACHINE",&_GUMBALLMACHINE,GUMBALLMACHINE__STATIC,GUMBALLMACHINE},
    {"GUMBALLMACHINEBROKE",&_GUMBALLMACHINEBROKE,GUMBALLMACHINEBROKE__STATIC,GUMBALLMACHINEBROKE},
    {"PAPER",&_PAPER,PAPER__STATIC,PAPER},
    {"MACE",&_MACE,MACE__STATIC,MACE},
    {"GENERICPOLE2",&_GENERICPOLE2,GENERICPOLE2__STATIC,GENERICPOLE2},
    {"XXXSTACY",&_XXXSTACY,XXXSTACY__STATIC,XXXSTACY},
    {"WETFLOOR",&_WETFLOOR,WETFLOOR__STATIC,WETFLOOR},
    {"BROOM",&_BROOM,BROOM__STATIC,BROOM},
    {"MOP",&_MOP,MOP__STATIC,MOP},
    {"LETTER",&_LETTER,LETTER__STATIC,LETTER},
    {"PIRATE1A",&_PIRATE1A,PIRATE1A__STATIC,PIRATE1A},
    {"PIRATE4A",&_PIRATE4A,PIRATE4A__STATIC,PIRATE4A},
    {"PIRATE2A",&_PIRATE2A,PIRATE2A__STATIC,PIRATE2A},
    {"PIRATE5A",&_PIRATE5A,PIRATE5A__STATIC,PIRATE5A},
    {"PIRATE3A",&_PIRATE3A,PIRATE3A__STATIC,PIRATE3A},
    {"PIRATE6A",&_PIRATE6A,PIRATE6A__STATIC,PIRATE6A},
    {"PIRATEHALF",&_PIRATEHALF,PIRATEHALF__STATIC,PIRATEHALF},
    {"CHESTOFGOLD",&_CHESTOFGOLD,CHESTOFGOLD__STATIC,CHESTOFGOLD},
    {"SIDEBOLT1",&_SIDEBOLT1,SIDEBOLT1__STATIC,SIDEBOLT1},
    {"FOODOBJECT1",&_FOODOBJECT1,FOODOBJECT1__STATIC,FOODOBJECT1},
    {"FOODOBJECT2",&_FOODOBJECT2,FOODOBJECT2__STATIC,FOODOBJECT2},
    {"FOODOBJECT3",&_FOODOBJECT3,FOODOBJECT3__STATIC,FOODOBJECT3},
    {"FOODOBJECT4",&_FOODOBJECT4,FOODOBJECT4__STATIC,FOODOBJECT4},
    {"FOODOBJECT5",&_FOODOBJECT5,FOODOBJECT5__STATIC,FOODOBJECT5},
    {"FOODOBJECT6",&_FOODOBJECT6,FOODOBJECT6__STATIC,FOODOBJECT6},
    {"FOODOBJECT7",&_FOODOBJECT7,FOODOBJECT7__STATIC,FOODOBJECT7},
    {"FOODOBJECT8",&_FOODOBJECT8,FOODOBJECT8__STATIC,FOODOBJECT8},
    {"FOODOBJECT9",&_FOODOBJECT9,FOODOBJECT9__STATIC,FOODOBJECT9},
    {"FOODOBJECT10",&_FOODOBJECT10,FOODOBJECT10__STATIC,FOODOBJECT10},
    {"FOODOBJECT11",&_FOODOBJECT11,FOODOBJECT11__STATIC,FOODOBJECT11},
    {"FOODOBJECT12",&_FOODOBJECT12,FOODOBJECT12__STATIC,FOODOBJECT12},
    {"FOODOBJECT13",&_FOODOBJECT13,FOODOBJECT13__STATIC,FOODOBJECT13},
    {"FOODOBJECT14",&_FOODOBJECT14,FOODOBJECT14__STATIC,FOODOBJECT14},
    {"FOODOBJECT15",&_FOODOBJECT15,FOODOBJECT15__STATIC,FOODOBJECT15},
    {"FOODOBJECT16",&_FOODOBJECT16,FOODOBJECT16__STATIC,FOODOBJECT16},
    {"FOODOBJECT17",&_FOODOBJECT17,FOODOBJECT17__STATIC,FOODOBJECT17},
    {"FOODOBJECT18",&_FOODOBJECT18,FOODOBJECT18__STATIC,FOODOBJECT18},
    {"FOODOBJECT19",&_FOODOBJECT19,FOODOBJECT19__STATIC,FOODOBJECT19},
    {"FOODOBJECT20",&_FOODOBJECT20,FOODOBJECT20__STATIC,FOODOBJECT20},
    {"HEADLAMP",&_HEADLAMP,HEADLAMP__STATIC,HEADLAMP},
    {"TAMPON",&_TAMPON,TAMPON__STATIC,TAMPON},
    {"SKINNEDCHICKEN",&_SKINNEDCHICKEN,SKINNEDCHICKEN__STATIC,SKINNEDCHICKEN},
    {"FEATHEREDCHICKEN",&_FEATHEREDCHICKEN,FEATHEREDCHICKEN__STATIC,FEATHEREDCHICKEN},
    {"ROBOTDOG2",&_ROBOTDOG2,ROBOTDOG2__STATIC,ROBOTDOG2},
    {"JOLLYMEAL",&_JOLLYMEAL,JOLLYMEAL__STATIC,JOLLYMEAL},
    {"DUKEBURGER",&_DUKEBURGER,DUKEBURGER__STATIC,DUKEBURGER},
    {"SHOPPINGCART",&_SHOPPINGCART,SHOPPINGCART__STATIC,SHOPPINGCART},
    {"CANWITHSOMETHING2",&_CANWITHSOMETHING2,CANWITHSOMETHING2__STATIC,CANWITHSOMETHING2},
    {"CANWITHSOMETHING3",&_CANWITHSOMETHING3,CANWITHSOMETHING3__STATIC,CANWITHSOMETHING3},
    {"CANWITHSOMETHING4",&_CANWITHSOMETHING4,CANWITHSOMETHING4__STATIC,CANWITHSOMETHING4},
    {"SNAKEP",&_SNAKEP,SNAKEP__STATIC,SNAKEP},
    {"DOLPHIN1",&_DOLPHIN1,DOLPHIN1__STATIC,DOLPHIN1},
    {"DOLPHIN2",&_DOLPHIN2,DOLPHIN2__STATIC,DOLPHIN2},

    {"FEM10",&_FEM10,FEM10__STATIC,FEM10},
    {"TOUGHGAL",&_TOUGHGAL,TOUGHGAL__STATIC,TOUGHGAL},
    {"MAN",&_MAN,MAN__STATIC,MAN},
    {"MAN2",&_MAN2,MAN2__STATIC,MAN2},
    {"WOMAN",&_WOMAN,WOMAN__STATIC,WOMAN},
    {"PLEASEWAIT",&_PLEASEWAIT,PLEASEWAIT__STATIC,PLEASEWAIT},
    {"NATURALLIGHTNING",&_NATURALLIGHTNING,NATURALLIGHTNING__STATIC,NATURALLIGHTNING},
    {"WEATHERWARN",&_WEATHERWARN,WEATHERWARN__STATIC,WEATHERWARN},
    {"DUKETAG",&_DUKETAG,DUKETAG__STATIC,DUKETAG},
    {"SIGN1",&_SIGN1,SIGN1__STATIC,SIGN1},
    {"SIGN2",&_SIGN2,SIGN2__STATIC,SIGN2},
    {"JURYGUY",&_JURYGUY,JURYGUY__STATIC,JURYGUY},
    {"RESERVEDSLOT1",&_RESERVEDSLOT1,RESERVEDSLOT1__STATIC,RESERVEDSLOT1},
    {"RESERVEDSLOT2",&_RESERVEDSLOT2,RESERVEDSLOT2__STATIC,RESERVEDSLOT2},
    {"RESERVEDSLOT3",&_RESERVEDSLOT3,RESERVEDSLOT3__STATIC,RESERVEDSLOT3},
    {"RESERVEDSLOT4",&_RESERVEDSLOT4,RESERVEDSLOT4__STATIC,RESERVEDSLOT4},
    {"RESERVEDSLOT5",&_RESERVEDSLOT5,RESERVEDSLOT5__STATIC,RESERVEDSLOT5},
    {"RESERVEDSLOT6",&_RESERVEDSLOT6,RESERVEDSLOT6__STATIC,RESERVEDSLOT6},
    {"RESERVEDSLOT7",&_RESERVEDSLOT7,RESERVEDSLOT7__STATIC,RESERVEDSLOT7},
    {"RESERVEDSLOT8",&_RESERVEDSLOT8,RESERVEDSLOT8__STATIC,RESERVEDSLOT8},
    {"RESERVEDSLOT9",&_RESERVEDSLOT9,RESERVEDSLOT9__STATIC,RESERVEDSLOT9},
    {"RESERVEDSLOT10",&_RESERVEDSLOT10,RESERVEDSLOT10__STATIC,RESERVEDSLOT10},
    {"RESERVEDSLOT11",&_RESERVEDSLOT11,RESERVEDSLOT11__STATIC,RESERVEDSLOT11},
    {"RESERVEDSLOT12",&_RESERVEDSLOT12,RESERVEDSLOT12__STATIC,RESERVEDSLOT12},
    {0,NULL,0,0},
};

int16_t DynamicTileMap[MAXTILES];

void G_ProcessDynamicTileMapping(const char *szLabel, int32_t lValue) {
    int32_t i;
    if (lValue >= MAXTILES || !szLabel)
        return;

    i = hash_find(&dynnamesH,szLabel);
    if (i>=0) *(list[i].v)=lValue;
}

void inithashnames() {
    int32_t i;
    hash_init(&dynnamesH);
    for (i=0; list[i].val; i++)
        hash_add(&dynnamesH,list[i].s,i);
}

void freehashnames() {
    hash_free(&dynnamesH);
}

void G_InitDynamicTiles(void) {
    int32_t i = 0;
    clearbufbyte(DynamicTileMap,MAXTILES,0);
    while (list[i].val) {
        DynamicTileMap[list[i].val]=list[i].vstat;
        i++;
    }

    BlimpSpawnSprites[0] = _RPGSPRITE;
    BlimpSpawnSprites[1] = _CHAINGUNSPRITE;
    BlimpSpawnSprites[2] = _TEATGUNAMMO;
    BlimpSpawnSprites[3] = _RPGAMMO;
    BlimpSpawnSprites[4] = _RPGAMMO;
    BlimpSpawnSprites[5] = _JETPACK;
    BlimpSpawnSprites[6] = _SHIELD;
    BlimpSpawnSprites[7] = _FIRSTAID;
    BlimpSpawnSprites[8] = _STEROIDS;
    BlimpSpawnSprites[9] = _RPGAMMO;
    BlimpSpawnSprites[10] = _RPGAMMO;
    BlimpSpawnSprites[11] = _RPGSPRITE;
    BlimpSpawnSprites[12] = _RPGAMMO;
    BlimpSpawnSprites[13] = _BUZSAWSPRITE;
    BlimpSpawnSprites[14] = _BUZSAWAMMO;

    WeaponPickupSprites[0] = _KNEE;
    WeaponPickupSprites[1] = _FIRSTGUNSPRITE;
    WeaponPickupSprites[2] = _SHOTGUNSPRITE;
    WeaponPickupSprites[3] = _CHAINGUNSPRITE;
    WeaponPickupSprites[4] = _RPGSPRITE;
    WeaponPickupSprites[5] = _HEAVYHBOMB;
    WeaponPickupSprites[6] = _ALIENARMGUNSPRITE;
    WeaponPickupSprites[7] = _TEATGUNSPRITE;
    WeaponPickupSprites[8] = _POWDERKEGSPRITE;
    WeaponPickupSprites[9] = _BUZSAWSPRITE;
    WeaponPickupSprites[10] = _HEAVYHBOMB;
    WeaponPickupSprites[11] = _ALIENARMGUNSPRITE;
}
